module Advent.Day2
  ( day2TestData
  , day2ActualData
  , day2IsValid1
  , day2IsValid2
  , day2ValidCount
  )
 where

import Data.Algebra.Boolean (xor)
import Safe (headMay)

data Pwd = Pwd
  { minC :: Int
  , maxC :: Int
  , ch :: Char
  , pwd :: String
  }

day2ValidCount :: (Pwd -> Bool) -> [Pwd] -> Int
day2ValidCount f = length . filter f

day2IsValid1 :: Pwd -> Bool
day2IsValid1 p = l >= minC p && l <= maxC p
  where
    l = length (filter (== ch p) (pwd p))

day2IsValid2 :: Pwd -> Bool
day2IsValid2 p = (a == c `xor` b == c)
  where
    a = headMay (drop (minC p - 1) (pwd p))
    b = headMay (drop (maxC p - 1) (pwd p))
    c = Just (ch p)

day2TestData :: [Pwd]
day2TestData = 
  [ Pwd { minC = 1, maxC = 3, ch = 'a', pwd = "abcde" }
  , Pwd { minC = 1, maxC = 3, ch = 'b', pwd = "cdefg" }
  , Pwd { minC = 2, maxC = 9, ch = 'c', pwd = "ccccccccc" }
  ]

day2ActualData :: [Pwd]
day2ActualData =   
  [ Pwd { minC = 3, maxC = 11 , ch = 'z', pwd = "zzzzzdzzzzlzz" }
  , Pwd { minC = 3, maxC = 7 , ch = 'x', pwd = "xjxbgpxxgtx" }
  , Pwd { minC = 3, maxC = 4 , ch = 'v', pwd = "vvmv" }
  , Pwd { minC = 3, maxC = 5 , ch = 't', pwd = "tgkfq" }
  , Pwd { minC = 9, maxC = 10 , ch = 'j', pwd = "jjjjjjjjqjjjj" }
  , Pwd { minC = 5, maxC = 7 , ch = 'r', pwd = "rnhrhrr" }
  , Pwd { minC = 2, maxC = 6 , ch = 'n', pwd = "gnntnnsnnqjsbrn" }
  , Pwd { minC = 3, maxC = 4 , ch = 'g', pwd = "vrggfvxsgmggkgsm" }
  , Pwd { minC = 1, maxC = 4 , ch = 'c', pwd = "brccqr" }
  , Pwd { minC = 1, maxC = 5 , ch = 'h', pwd = "hhhzzvcdhhhhhhhh" }
  , Pwd { minC = 4, maxC = 11 , ch = 'c', pwd = "ncnqbzlkckc" }
  , Pwd { minC = 1, maxC = 13 , ch = 'q', pwd = "hqqqqqqqqqqqlq" }
  , Pwd { minC = 8, maxC = 9 , ch = 'h', pwd = "hhhhhhxxkh" }
  , Pwd { minC = 3, maxC = 9 , ch = 'b', pwd = "bbbbsfbbc" }
  , Pwd { minC = 3, maxC = 8 , ch = 'k', pwd = "zfqzkzgk" }
  , Pwd { minC = 3, maxC = 9 , ch = 'k', pwd = "wjkwhnkkfvxk" }
  , Pwd { minC = 3, maxC = 11 , ch = 'v', pwd = "vgkvvcjvvvv" }
  , Pwd { minC = 5, maxC = 6 , ch = 'l', pwd = "llllhr" }
  , Pwd { minC = 9, maxC = 11 , ch = 'z', pwd = "lzzzgzzmzzdzzz" }
  , Pwd { minC = 13, maxC = 16 , ch = 'w', pwd = "wwlwwwwlwwxwwfwf" }
  , Pwd { minC = 8, maxC = 11 , ch = 'r', pwd = "rrrrrrrrrrcrdrr" }
  , Pwd { minC = 1, maxC = 9 , ch = 'v', pwd = "mlvvvxnwrwvv" }
  , Pwd { minC = 4, maxC = 6 , ch = 'z', pwd = "mzzzzz" }
  , Pwd { minC = 3, maxC = 4 , ch = 's', pwd = "svsj" }
  , Pwd { minC = 8, maxC = 11 , ch = 'w', pwd = "wwwwwwwjwwww" }
  , Pwd { minC = 10, maxC = 13 , ch = 'r', pwd = "drrrrzhmxfjdrtfgr" }
  , Pwd { minC = 19, maxC = 20 , ch = 'h', pwd = "hhhhhhhhhhhhhhhhhhfh" }
  , Pwd { minC = 1, maxC = 4 , ch = 'z', pwd = "nzzcz" }
  , Pwd { minC = 10, maxC = 11 , ch = 'd', pwd = "ddldddddxdfdd" }
  , Pwd { minC = 10, maxC = 14 , ch = 'd', pwd = "dddddcddndkddd" }
  , Pwd { minC = 7, maxC = 15 , ch = 'h', pwd = "hhhhhhhhhhhhhhhhh" }
  , Pwd { minC = 1, maxC = 9 , ch = 'h', pwd = "rhhhhhhhhh" }
  , Pwd { minC = 3, maxC = 4 , ch = 'm', pwd = "mmztmm" }
  , Pwd { minC = 4, maxC = 6 , ch = 'w', pwd = "wmwxcwwlwwj" }
  , Pwd { minC = 7, maxC = 15 , ch = 'g', pwd = "ggggggggggnggglgg" }
  , Pwd { minC = 9, maxC = 14 , ch = 'n', pwd = "ntnnnnqnnnnnng" }
  , Pwd { minC = 2, maxC = 3 , ch = 'f', pwd = "fffl" }
  , Pwd { minC = 1, maxC = 7 , ch = 'b', pwd = "bjsqsbbzblt" }
  , Pwd { minC = 3, maxC = 6 , ch = 'c', pwd = "cckccccc" }
  , Pwd { minC = 4, maxC = 9 , ch = 'z', pwd = "hhgtvzszb" }
  , Pwd { minC = 1, maxC = 7 , ch = 'l', pwd = "tlllllll" }
  , Pwd { minC = 2, maxC = 3 , ch = 'v', pwd = "mknzrq" }
  , Pwd { minC = 12, maxC = 18 , ch = 'w', pwd = "wwwwwwwwwnwwwwwwwsww" }
  , Pwd { minC = 5, maxC = 8 , ch = 'k', pwd = "kkkgkjkdkrwgk" }
  , Pwd { minC = 10, maxC = 12 , ch = 'z', pwd = "gczzgvzzpzwzzzzzf" }
  , Pwd { minC = 11, maxC = 12 , ch = 'x', pwd = "xxxxxxxxxnqxxnxx" }
  , Pwd { minC = 4, maxC = 7 , ch = 'c', pwd = "chccccgccccscpcc" }
  , Pwd { minC = 7, maxC = 9 , ch = 'k', pwd = "kqbkxhkkkkkscfr" }
  , Pwd { minC = 2, maxC = 4 , ch = 'r', pwd = "rrrrr" }
  , Pwd { minC = 3, maxC = 5 , ch = 'p', pwd = "lwhwp" }
  , Pwd { minC = 11, maxC = 13 , ch = 'r', pwd = "pfjmrrdqnbrwrn" }
  , Pwd { minC = 4, maxC = 8 , ch = 'l', pwd = "nkpmjlrbtsxdzkqjqj" }
  , Pwd { minC = 1, maxC = 10 , ch = 'k', pwd = "kkbdtkkqrkkkkkknklk" }
  , Pwd { minC = 16, maxC = 17 , ch = 'b', pwd = "cxtqsbfbtkxqbprzbbgr" }
  , Pwd { minC = 7, maxC = 9 , ch = 'x', pwd = "xlgxdxxtqhxkbnxw" }
  , Pwd { minC = 5, maxC = 6 , ch = 'k', pwd = "kbkqkqkk" }
  , Pwd { minC = 6, maxC = 9 , ch = 's', pwd = "sbssspssk" }
  , Pwd { minC = 13, maxC = 17 , ch = 'p', pwd = "pzrpphmphgpkpbppj" }
  , Pwd { minC = 2, maxC = 8 , ch = 'r', pwd = "ttbrrmrfr" }
  , Pwd { minC = 16, maxC = 17 , ch = 'c', pwd = "cccccscckccccccvccc" }
  , Pwd { minC = 4, maxC = 5 , ch = 'v', pwd = "hvvmv" }
  , Pwd { minC = 4, maxC = 12 , ch = 's', pwd = "swssssssssshjsszrss" }
  , Pwd { minC = 9, maxC = 10 , ch = 'q', pwd = "qgqqqjqjkqhqq" }
  , Pwd { minC = 2, maxC = 4 , ch = 's', pwd = "rwtknhj" }
  , Pwd { minC = 3, maxC = 8 , ch = 's', pwd = "rbstpgqdslkvkkzprdzp" }
  , Pwd { minC = 8, maxC = 9 , ch = 'd', pwd = "ddsddvdpd" }
  , Pwd { minC = 1, maxC = 2 , ch = 'r', pwd = "rkrrrrrtrrdnrr" }
  , Pwd { minC = 7, maxC = 8 , ch = 'v', pwd = "vfpfrmltllx" }
  , Pwd { minC = 2, maxC = 3 , ch = 'k', pwd = "knkrk" }
  , Pwd { minC = 4, maxC = 5 , ch = 'f', pwd = "pwrbffffc" }
  , Pwd { minC = 7, maxC = 9 , ch = 'n', pwd = "nnntnnnpnbjjn" }
  , Pwd { minC = 6, maxC = 13 , ch = 'r', pwd = "rrrrrrrrrrrrrr" }
  , Pwd { minC = 5, maxC = 8 , ch = 'g', pwd = "bfgzlbmgjn" }
  , Pwd { minC = 3, maxC = 4 , ch = 'q', pwd = "tqhq" }
  , Pwd { minC = 13, maxC = 16 , ch = 'm', pwd = "mmmmkmmmmmmmmmmmmmm" }
  , Pwd { minC = 1, maxC = 5 , ch = 'w', pwd = "wwwwhhwgwfgfkvwqbx" }
  , Pwd { minC = 4, maxC = 7 , ch = 'n', pwd = "nbjnnnqnbpc" }
  , Pwd { minC = 12, maxC = 14 , ch = 'g', pwd = "ggggggggghgbgk" }
  , Pwd { minC = 14, maxC = 15 , ch = 'b', pwd = "bdbbbxbdbzjtbcs" }
  , Pwd { minC = 8, maxC = 9 , ch = 'z', pwd = "zdfzxzkpz" }
  , Pwd { minC = 19, maxC = 20 , ch = 'r', pwd = "xbpdfrkmtgzrrqrrjrrr" }
  , Pwd { minC = 9, maxC = 12 , ch = 'f', pwd = "ffffffqfpgvzgfnf" }
  , Pwd { minC = 11, maxC = 12 , ch = 'm', pwd = "mmmmmmtmmmmm" }
  , Pwd { minC = 6, maxC = 7 , ch = 'q', pwd = "lbqqqqtb" }
  , Pwd { minC = 6, maxC = 10 , ch = 'g', pwd = "gggggtgggmgggg" }
  , Pwd { minC = 9, maxC = 16 , ch = 'p', pwd = "prppzppdppppkpjfpc" }
  , Pwd { minC = 1, maxC = 3 , ch = 'x', pwd = "xkrbrxdvrncxd" }
  , Pwd { minC = 17, maxC = 18 , ch = 'b', pwd = "bvpbnbrgvjcbbkjrbj" }
  , Pwd { minC = 13, maxC = 18 , ch = 'd', pwd = "dddmddddjdtdddddddd" }
  , Pwd { minC = 3, maxC = 4 , ch = 'z', pwd = "zzdzc" }
  , Pwd { minC = 8, maxC = 9 , ch = 'm', pwd = "mmmmmmmpm" }
  , Pwd { minC = 4, maxC = 10 , ch = 'v', pwd = "rvzqvrvvgvqvv" }
  , Pwd { minC = 1, maxC = 9 , ch = 'q', pwd = "jnhbqjlvq" }
  , Pwd { minC = 5, maxC = 13 , ch = 'd', pwd = "sddkhdjddkddpkvdsw" }
  , Pwd { minC = 5, maxC = 9 , ch = 'd', pwd = "dppdpddtmvl" }
  , Pwd { minC = 5, maxC = 7 , ch = 's', pwd = "knzhssbxsjcssnsqb" }
  , Pwd { minC = 10, maxC = 15 , ch = 'p', pwd = "ppgvpppvplpppxpcp" }
  , Pwd { minC = 5, maxC = 6 , ch = 'c', pwd = "cczccv" }
  , Pwd { minC = 5, maxC = 6 , ch = 'q', pwd = "dqlvjfqqqqmqxq" }
  , Pwd { minC = 8, maxC = 10 , ch = 'j', pwd = "jjjjjwjxgknjfjj" }
  , Pwd { minC = 7, maxC = 16 , ch = 'x', pwd = "xxxxxxxxxxxxxxxcx" }
  , Pwd { minC = 9, maxC = 13 , ch = 'h', pwd = "hhhhzvwhhbhhhhljhh" }
  , Pwd { minC = 6, maxC = 7 , ch = 'v', pwd = "wvzxlvt" }
  , Pwd { minC = 16, maxC = 18 , ch = 'f', pwd = "fsffbffffpffffflfff" }
  , Pwd { minC = 1, maxC = 5 , ch = 'r', pwd = "rhrvrprwwb" }
  , Pwd { minC = 5, maxC = 8 , ch = 'h', pwd = "hhhhhhhjh" }
  , Pwd { minC = 3, maxC = 6 , ch = 'p', pwd = "ppgppsp" }
  , Pwd { minC = 15, maxC = 17 , ch = 'r', pwd = "rrrrrrrcrrrrlrrrb" }
  , Pwd { minC = 3, maxC = 6 , ch = 'm', pwd = "jhzmtmbnwh" }
  , Pwd { minC = 6, maxC = 9 , ch = 'r', pwd = "rhfjdrrhrg" }
  , Pwd { minC = 15, maxC = 17 , ch = 'l', pwd = "gqngllrsxrlpxblfl" }
  , Pwd { minC = 2, maxC = 12 , ch = 'w', pwd = "wwwwwwwwwwwww" }
  , Pwd { minC = 2, maxC = 3 , ch = 'c', pwd = "cpncdqzp" }
  , Pwd { minC = 3, maxC = 4 , ch = 'f', pwd = "ffllffqjf" }
  , Pwd { minC = 1, maxC = 9 , ch = 'c', pwd = "ccccccccbcc" }
  , Pwd { minC = 19, maxC = 20 , ch = 'x', pwd = "xxxxxxxwxxxxxxxxxxvx" }
  , Pwd { minC = 3, maxC = 4 , ch = 'p', pwd = "pplvs" }
  , Pwd { minC = 2, maxC = 3 , ch = 's', pwd = "ftss" }
  , Pwd { minC = 11, maxC = 12 , ch = 's', pwd = "ssdsssgsssths" }
  , Pwd { minC = 4, maxC = 11 , ch = 'm', pwd = "mmgmpmsqrmmmbwmm" }
  , Pwd { minC = 2, maxC = 4 , ch = 'x', pwd = "xhrk" }
  , Pwd { minC = 6, maxC = 8 , ch = 'g', pwd = "gggvgggv" }
  , Pwd { minC = 8, maxC = 14 , ch = 'h', pwd = "whhhlhhdhhhlhhh" }
  , Pwd { minC = 5, maxC = 16 , ch = 'g', pwd = "fnxpglggbrsgscqmzlfq" }
  , Pwd { minC = 5, maxC = 11 , ch = 'h', pwd = "hnhhhhhhhhthmh" }
  , Pwd { minC = 5, maxC = 7 , ch = 'x', pwd = "xvxxxxxqxw" }
  , Pwd { minC = 1, maxC = 3 , ch = 'm', pwd = "mnbt" }
  , Pwd { minC = 1, maxC = 6 , ch = 'g', pwd = "bgggbwghg" }
  , Pwd { minC = 1, maxC = 6 , ch = 'f', pwd = "sptjzfxcfw" }
  , Pwd { minC = 9, maxC = 12 , ch = 'g', pwd = "ggzgggggvgtjgg" }
  , Pwd { minC = 2, maxC = 4 , ch = 'q', pwd = "qlrvx" }
  , Pwd { minC = 4, maxC = 5 , ch = 'j', pwd = "jjjgj" }
  , Pwd { minC = 1, maxC = 3 , ch = 'g', pwd = "htmg" }
  , Pwd { minC = 6, maxC = 8 , ch = 'j', pwd = "jjjjjmjjjjjj" }
  , Pwd { minC = 12, maxC = 14 , ch = 'h', pwd = "xhhhhhhhhhhlhhfhh" }
  , Pwd { minC = 9, maxC = 11 , ch = 'h', pwd = "hkvhhgvhhhrshml" }
  , Pwd { minC = 12, maxC = 13 , ch = 'j', pwd = "jjjljjtjpjjjgj" }
  , Pwd { minC = 6, maxC = 7 , ch = 'r', pwd = "drqdrrvr" }
  , Pwd { minC = 6, maxC = 17 , ch = 'q', pwd = "qqqlqqqqqqqqqqqqbqqq" }
  , Pwd { minC = 6, maxC = 7 , ch = 'j', pwd = "vjjrvjjjwzj" }
  , Pwd { minC = 11, maxC = 12 , ch = 'v', pwd = "vtvvvjvvvvgvv" }
  , Pwd { minC = 6, maxC = 8 , ch = 'x', pwd = "xxxbcbxl" }
  , Pwd { minC = 3, maxC = 9 , ch = 'f', pwd = "fffffffff" }
  , Pwd { minC = 9, maxC = 10 , ch = 'c', pwd = "cccsccllrktqccfjzz" }
  , Pwd { minC = 2, maxC = 5 , ch = 's', pwd = "ssssqn" }
  , Pwd { minC = 8, maxC = 15 , ch = 'x', pwd = "brlmqdmpfdqgmgptgxd" }
  , Pwd { minC = 1, maxC = 4 , ch = 't', pwd = "ttlcttw" }
  , Pwd { minC = 5, maxC = 6 , ch = 'c', pwd = "cqccnc" }
  , Pwd { minC = 10, maxC = 11 , ch = 'm', pwd = "mqmmmmmmhvvlrmm" }
  , Pwd { minC = 3, maxC = 4 , ch = 'j', pwd = "jjhjwbjj" }
  , Pwd { minC = 10, maxC = 11 , ch = 'c', pwd = "ccccccccckd" }
  , Pwd { minC = 6, maxC = 8 , ch = 'h', pwd = "xhhchhfchh" }
  , Pwd { minC = 9, maxC = 10 , ch = 'n', pwd = "rnnnnnnncnnnn" }
  , Pwd { minC = 1, maxC = 4 , ch = 'l', pwd = "lvslw" }
  , Pwd { minC = 3, maxC = 4 , ch = 's', pwd = "spfs" }
  , Pwd { minC = 11, maxC = 13 , ch = 'n', pwd = "fqtdnnnnnlnnx" }
  , Pwd { minC = 6, maxC = 7 , ch = 'g', pwd = "xdgxggp" }
  , Pwd { minC = 7, maxC = 8 , ch = 'r', pwd = "xhrnqlrr" }
  , Pwd { minC = 1, maxC = 12 , ch = 'r', pwd = "rrrrnwwrbrbrhrjxr" }
  , Pwd { minC = 14, maxC = 15 , ch = 'b', pwd = "chmbmkxngftlfbf" }
  , Pwd { minC = 1, maxC = 3 , ch = 'm', pwd = "fmmgmdgs" }
  , Pwd { minC = 5, maxC = 7 , ch = 'w', pwd = "fwwwswwwwwgw" }
  , Pwd { minC = 10, maxC = 14 , ch = 'l', pwd = "qlllgzljczmpls" }
  , Pwd { minC = 1, maxC = 2 , ch = 'k', pwd = "kkkq" }
  , Pwd { minC = 5, maxC = 6 , ch = 't', pwd = "tttttt" }
  , Pwd { minC = 9, maxC = 16 , ch = 'r', pwd = "gpdtlxhntjfjjtlsxd" }
  , Pwd { minC = 4, maxC = 5 , ch = 'g', pwd = "kgjrhjmszxg" }
  , Pwd { minC = 4, maxC = 5 , ch = 'z', pwd = "zmszpklzsvz" }
  , Pwd { minC = 1, maxC = 2 , ch = 'j', pwd = "mfjjb" }
  , Pwd { minC = 3, maxC = 6 , ch = 's', pwd = "sfxlzslsrszcsstsrb" }
  , Pwd { minC = 3, maxC = 4 , ch = 'n', pwd = "knlvnnkq" }
  , Pwd { minC = 1, maxC = 2 , ch = 's', pwd = "jsst" }
  , Pwd { minC = 3, maxC = 4 , ch = 'n', pwd = "nsnm" }
  , Pwd { minC = 1, maxC = 2 , ch = 'm', pwd = "wzgczk" }
  , Pwd { minC = 10, maxC = 11 , ch = 'b', pwd = "btnnwgbgtht" }
  , Pwd { minC = 2, maxC = 7 , ch = 'd', pwd = "qcrdlgdgc" }
  , Pwd { minC = 10, maxC = 13 , ch = 'w', pwd = "wxwwdrwwwtdwwwswh" }
  , Pwd { minC = 2, maxC = 3 , ch = 'c', pwd = "cckcd" }
  , Pwd { minC = 3, maxC = 6 , ch = 'p', pwd = "ppqppppp" }
  , Pwd { minC = 1, maxC = 6 , ch = 'n', pwd = "nmsnjdn" }
  , Pwd { minC = 2, maxC = 3 , ch = 'h', pwd = "hhrhj" }
  , Pwd { minC = 11, maxC = 12 , ch = 'w', pwd = "wwwwwwwwwbvwwwwwh" }
  , Pwd { minC = 1, maxC = 14 , ch = 'c', pwd = "zkctkncccccfcccpccc" }
  , Pwd { minC = 6, maxC = 7 , ch = 'm', pwd = "zqvdkmnztcvmdrgbw" }
  , Pwd { minC = 1, maxC = 13 , ch = 'q', pwd = "qgmqhfgphjzrt" }
  , Pwd { minC = 6, maxC = 7 , ch = 'l', pwd = "llllljdv" }
  , Pwd { minC = 2, maxC = 5 , ch = 'k', pwd = "jspjkkkk" }
  , Pwd { minC = 7, maxC = 15 , ch = 'p', pwd = "ppppppvppppppppppp" }
  , Pwd { minC = 12, maxC = 16 , ch = 'k', pwd = "klkkkkkvkkzxkkkg" }
  , Pwd { minC = 8, maxC = 17 , ch = 'x', pwd = "xrxxnxxxsxvvxwbwzl" }
  , Pwd { minC = 11, maxC = 14 , ch = 's', pwd = "ssssssssssssst" }
  , Pwd { minC = 8, maxC = 15 , ch = 'z', pwd = "cfznhznzwnzzrmm" }
  , Pwd { minC = 5, maxC = 7 , ch = 'q', pwd = "rqpnqwqvw" }
  , Pwd { minC = 2, maxC = 9 , ch = 'c', pwd = "zrpcmsclcbxtkbjvjc" }
  , Pwd { minC = 5, maxC = 12 , ch = 'c', pwd = "ccccpccccccjcccc" }
  , Pwd { minC = 3, maxC = 8 , ch = 'w', pwd = "hwswwrwwww" }
  , Pwd { minC = 4, maxC = 9 , ch = 'p', pwd = "wphzppzxpkxpbpzsplp" }
  , Pwd { minC = 4, maxC = 5 , ch = 'q', pwd = "rqqcqw" }
  , Pwd { minC = 11, maxC = 14 , ch = 'k', pwd = "kkckkkkwkkkkkdkk" }
  , Pwd { minC = 2, maxC = 5 , ch = 'v', pwd = "sqvvpvxvqgvvvzr" }
  , Pwd { minC = 5, maxC = 10 , ch = 'f', pwd = "ffffzffffjff" }
  , Pwd { minC = 4, maxC = 6 , ch = 'b', pwd = "bhbbjk" }
  , Pwd { minC = 4, maxC = 8 , ch = 'z', pwd = "zxzzzdzrzz" }
  , Pwd { minC = 4, maxC = 8 , ch = 'h', pwd = "hhhhfscrnhthppkkvh" }
  , Pwd { minC = 2, maxC = 3 , ch = 'w', pwd = "wgvwwjwwww" }
  , Pwd { minC = 3, maxC = 5 , ch = 'd', pwd = "dsdjddnndzbxtd" }
  , Pwd { minC = 5, maxC = 13 , ch = 'm', pwd = "mmmmfmmqmmmmmmm" }
  , Pwd { minC = 1, maxC = 2 , ch = 'l', pwd = "wglcs" }
  , Pwd { minC = 8, maxC = 9 , ch = 'r', pwd = "rrrrrrrsr" }
  , Pwd { minC = 8, maxC = 16 , ch = 'l', pwd = "lllllllllllllllll" }
  , Pwd { minC = 8, maxC = 10 , ch = 's', pwd = "fmqsscwtshsss" }
  , Pwd { minC = 2, maxC = 13 , ch = 'q', pwd = "qqqzqqnxvqqsqjzl" }
  , Pwd { minC = 5, maxC = 7 , ch = 'f', pwd = "vrwrfffcmjwsfdzffm" }
  , Pwd { minC = 2, maxC = 8 , ch = 'k', pwd = "hhsbmrkkfhkkxkkz" }
  , Pwd { minC = 12, maxC = 13 , ch = 'f', pwd = "ffffffcffffff" }
  , Pwd { minC = 4, maxC = 5 , ch = 'x', pwd = "pzrxwxbxxdgfnxg" }
  , Pwd { minC = 1, maxC = 5 , ch = 'c', pwd = "cccww" }
  , Pwd { minC = 8, maxC = 11 , ch = 'g', pwd = "dgggjrggggggg" }
  , Pwd { minC = 9, maxC = 14 , ch = 't', pwd = "httdgxxtthtsxtpsml" }
  , Pwd { minC = 7, maxC = 11 , ch = 'p', pwd = "pprppppppppp" }
  , Pwd { minC = 13, maxC = 16 , ch = 'm', pwd = "mmtkphqvkrzpwzsm" }
  , Pwd { minC = 12, maxC = 15 , ch = 'g', pwd = "gkzgggggggggggltb" }
  , Pwd { minC = 5, maxC = 7 , ch = 'k', pwd = "kkkkvkjkkk" }
  , Pwd { minC = 15, maxC = 17 , ch = 'p', pwd = "pppptpppppcjppppsp" }
  , Pwd { minC = 1, maxC = 5 , ch = 'z', pwd = "znzzz" }
  , Pwd { minC = 2, maxC = 14 , ch = 'j', pwd = "lnjjjghjjrjjjj" }
  , Pwd { minC = 3, maxC = 9 , ch = 'r', pwd = "rrvrrcrrr" }
  , Pwd { minC = 2, maxC = 4 , ch = 'm', pwd = "wggmmh" }
  , Pwd { minC = 4, maxC = 5 , ch = 'b', pwd = "bbbbrb" }
  , Pwd { minC = 2, maxC = 16 , ch = 'v', pwd = "vgvvvvvvvvvvvvvvv" }
  , Pwd { minC = 2, maxC = 15 , ch = 's', pwd = "rsswfmvsrdkjqjssl" }
  , Pwd { minC = 3, maxC = 6 , ch = 'b', pwd = "nbbbnbbbb" }
  , Pwd { minC = 2, maxC = 4 , ch = 'x', pwd = "pxxwj" }
  , Pwd { minC = 12, maxC = 13 , ch = 'c', pwd = "cccccccccccccc" }
  , Pwd { minC = 6, maxC = 8 , ch = 'g', pwd = "gggggpgvggg" }
  , Pwd { minC = 3, maxC = 6 , ch = 'j', pwd = "srljvjqpkjvtdrndkgjr" }
  , Pwd { minC = 7, maxC = 8 , ch = 'g', pwd = "gmggtcggz" }
  , Pwd { minC = 3, maxC = 7 , ch = 'p', pwd = "tmvpppkm" }
  , Pwd { minC = 4, maxC = 10 , ch = 'w', pwd = "qrwgmwdwlww" }
  , Pwd { minC = 6, maxC = 8 , ch = 'k', pwd = "kknckkkjkkk" }
  , Pwd { minC = 11, maxC = 14 , ch = 'g', pwd = "ggggggggzggggcgggggg" }
  , Pwd { minC = 11, maxC = 14 , ch = 'j', pwd = "jjjwjjjjtmjjjgjj" }
  , Pwd { minC = 7, maxC = 12 , ch = 'n', pwd = "njmntnnsbncknqnn" }
  , Pwd { minC = 5, maxC = 8 , ch = 't', pwd = "tbrttttctrt" }
  , Pwd { minC = 4, maxC = 6 , ch = 'f', pwd = "gffrffzffffffm" }
  , Pwd { minC = 4, maxC = 11 , ch = 'c', pwd = "pksccvlcsrcjgmzn" }
  , Pwd { minC = 2, maxC = 3 , ch = 'p', pwd = "vbcfdppzw" }
  , Pwd { minC = 2, maxC = 5 , ch = 'c', pwd = "lqfcc" }
  , Pwd { minC = 1, maxC = 2 , ch = 'h', pwd = "lhskgvhc" }
  , Pwd { minC = 10, maxC = 11 , ch = 'b', pwd = "bbbbbwbbbmc" }
  , Pwd { minC = 3, maxC = 15 , ch = 'n', pwd = "nkbtnlznnxffzjlpfm" }
  , Pwd { minC = 2, maxC = 5 , ch = 's', pwd = "ntsqc" }
  , Pwd { minC = 9, maxC = 11 , ch = 'l', pwd = "llllllllblfl" }
  , Pwd { minC = 9, maxC = 10 , ch = 'd', pwd = "ddcdfdbcqn" }
  , Pwd { minC = 8, maxC = 10 , ch = 'g', pwd = "htgcjhggzmnl" }
  , Pwd { minC = 5, maxC = 10 , ch = 'v', pwd = "vvqvvvvvvbvv" }
  , Pwd { minC = 2, maxC = 6 , ch = 'l', pwd = "lllfjdc" }
  , Pwd { minC = 3, maxC = 4 , ch = 'c', pwd = "gxtmsqdsps" }
  , Pwd { minC = 7, maxC = 8 , ch = 'f', pwd = "fffffbbm" }
  , Pwd { minC = 1, maxC = 6 , ch = 'z', pwd = "zlndzbf" }
  , Pwd { minC = 9, maxC = 11 , ch = 'g', pwd = "ggzgxgggkgggzd" }
  , Pwd { minC = 15, maxC = 16 , ch = 'n', pwd = "fflrvmnrvjnrznqgq" }
  , Pwd { minC = 1, maxC = 3 , ch = 'b', pwd = "lkbb" }
  , Pwd { minC = 2, maxC = 3 , ch = 'k', pwd = "kgkk" }
  , Pwd { minC = 9, maxC = 12 , ch = 'r', pwd = "skrrrrrjrmrhr" }
  , Pwd { minC = 10, maxC = 15 , ch = 'c', pwd = "ncccmccpvcqfcqgcfcj" }
  , Pwd { minC = 5, maxC = 13 , ch = 'r', pwd = "rrrrrrrrrrrrrrrr" }
  , Pwd { minC = 13, maxC = 14 , ch = 'b', pwd = "bbbbbbbbbbbbfb" }
  , Pwd { minC = 13, maxC = 18 , ch = 'l', pwd = "llvllllllpllllllbl" }
  , Pwd { minC = 4, maxC = 5 , ch = 'm', pwd = "mmmmqm" }
  , Pwd { minC = 5, maxC = 9 , ch = 'g', pwd = "ggrgcgggggggg" }
  , Pwd { minC = 1, maxC = 4 , ch = 'q', pwd = "qqqq" }
  , Pwd { minC = 1, maxC = 13 , ch = 'l', pwd = "llllllllllllll" }
  , Pwd { minC = 14, maxC = 18 , ch = 'g', pwd = "ggggdgpgggjfgmngggg" }
  , Pwd { minC = 13, maxC = 16 , ch = 'p', pwd = "pppphppppppppppv" }
  , Pwd { minC = 1, maxC = 7 , ch = 'f', pwd = "ftffffgffff" }
  , Pwd { minC = 8, maxC = 9 , ch = 's', pwd = "tbslsssjsqsssss" }
  , Pwd { minC = 8, maxC = 9 , ch = 's', pwd = "szmzsssss" }
  , Pwd { minC = 7, maxC = 8 , ch = 'l', pwd = "lllllllll" }
  , Pwd { minC = 4, maxC = 6 , ch = 't', pwd = "twtjrt" }
  , Pwd { minC = 3, maxC = 11 , ch = 'z', pwd = "zjzntzxzlzczdtz" }
  , Pwd { minC = 4, maxC = 8 , ch = 'c', pwd = "ccchcclc" }
  , Pwd { minC = 3, maxC = 11 , ch = 'l', pwd = "wvldjftflsgzcwllbbm" }
  , Pwd { minC = 1, maxC = 7 , ch = 'x', pwd = "xwjhmgxkqqtdx" }
  , Pwd { minC = 8, maxC = 12 , ch = 'c', pwd = "cccccccnccckcc" }
  , Pwd { minC = 2, maxC = 8 , ch = 'f', pwd = "nghfxvqtfrpwjf" }
  , Pwd { minC = 6, maxC = 7 , ch = 'b', pwd = "nbbbrbslsb" }
  , Pwd { minC = 3, maxC = 4 , ch = 'w', pwd = "zwnwdzqw" }
  , Pwd { minC = 7, maxC = 8 , ch = 'p', pwd = "tpppppnpppppp" }
  , Pwd { minC = 8, maxC = 9 , ch = 'q', pwd = "qwqqqjbft" }
  , Pwd { minC = 3, maxC = 4 , ch = 'z', pwd = "zztzn" }
  , Pwd { minC = 13, maxC = 14 , ch = 'f', pwd = "dfffffmxffffff" }
  , Pwd { minC = 3, maxC = 14 , ch = 't', pwd = "gnpksvbtpzxrsw" }
  , Pwd { minC = 12, maxC = 16 , ch = 'z', pwd = "zzzzzzzzzzzfzzzz" }
  , Pwd { minC = 2, maxC = 4 , ch = 'b', pwd = "mzbxbk" }
  , Pwd { minC = 5, maxC = 6 , ch = 'r', pwd = "rrrrpr" }
  , Pwd { minC = 5, maxC = 10 , ch = 'z', pwd = "cfflzmzxdc" }
  , Pwd { minC = 4, maxC = 5 , ch = 'l', pwd = "lvtvblll" }
  , Pwd { minC = 6, maxC = 19 , ch = 't', pwd = "tttttdtttttttttttttt" }
  , Pwd { minC = 7, maxC = 8 , ch = 'g', pwd = "gjgbtggjggg" }
  , Pwd { minC = 3, maxC = 5 , ch = 's', pwd = "sssssr" }
  , Pwd { minC = 8, maxC = 9 , ch = 's', pwd = "kssvfsssrsrssns" }
  , Pwd { minC = 2, maxC = 4 , ch = 'p', pwd = "gpbm" }
  , Pwd { minC = 1, maxC = 2 , ch = 'g', pwd = "gbjsl" }
  , Pwd { minC = 3, maxC = 4 , ch = 'k', pwd = "tdkn" }
  , Pwd { minC = 8, maxC = 9 , ch = 'z', pwd = "zzbglvpbrfml" }
  , Pwd { minC = 5, maxC = 13 , ch = 'm', pwd = "mmmmlmkmsmxzmpmmcmm" }
  , Pwd { minC = 16, maxC = 18 , ch = 'b', pwd = "lbbwbbbbbbbbbbbbsb" }
  , Pwd { minC = 2, maxC = 4 , ch = 's', pwd = "fgsstnssztbzkzcmp" }
  , Pwd { minC = 3, maxC = 9 , ch = 'l', pwd = "hvllztddtj" }
  , Pwd { minC = 4, maxC = 8 , ch = 'w', pwd = "wwzcwwwf" }
  , Pwd { minC = 11, maxC = 12 , ch = 'z', pwd = "zzzzzzzzzzck" }
  , Pwd { minC = 9, maxC = 10 , ch = 'q', pwd = "qmqqqqqqqw" }
  , Pwd { minC = 1, maxC = 8 , ch = 'x', pwd = "qpxxxxxrxxxcxvxt" }
  , Pwd { minC = 12, maxC = 16 , ch = 'l', pwd = "lllllllllllsllllllll" }
  , Pwd { minC = 4, maxC = 5 , ch = 'r', pwd = "rrrbt" }
  , Pwd { minC = 4, maxC = 6 , ch = 'v', pwd = "mjvwvvv" }
  , Pwd { minC = 5, maxC = 7 , ch = 'r', pwd = "rhrrrrrrr" }
  , Pwd { minC = 1, maxC = 2 , ch = 'v', pwd = "vgfvv" }
  , Pwd { minC = 4, maxC = 15 , ch = 'b', pwd = "bbblblbvbbbbslbbbcq" }
  , Pwd { minC = 14, maxC = 15 , ch = 'c', pwd = "cclcccccccccccc" }
  , Pwd { minC = 8, maxC = 20 , ch = 'h', pwd = "gzkhwrhrjdphrrhnjhcm" }
  , Pwd { minC = 5, maxC = 10 , ch = 'm', pwd = "mmmmtmkmmmmpmmhm" }
  , Pwd { minC = 2, maxC = 14 , ch = 'f', pwd = "kjcwnfhcqnwhbgm" }
  , Pwd { minC = 11, maxC = 13 , ch = 'm', pwd = "mzmvmmsmlmmppm" }
  , Pwd { minC = 3, maxC = 9 , ch = 'g', pwd = "kglkgdctgxxs" }
  , Pwd { minC = 2, maxC = 7 , ch = 's', pwd = "ssdglzsb" }
  , Pwd { minC = 7, maxC = 10 , ch = 'j', pwd = "jtjjjjjjkj" }
  , Pwd { minC = 12, maxC = 13 , ch = 'q', pwd = "hxhjqsqsqzqqmjnqks" }
  , Pwd { minC = 18, maxC = 19 , ch = 'f', pwd = "ffffffffffffffffffxf" }
  , Pwd { minC = 3, maxC = 11 , ch = 'v', pwd = "xhvtvnjcccnsvgzv" }
  , Pwd { minC = 8, maxC = 9 , ch = 'j', pwd = "jjjjxjjjrw" }
  , Pwd { minC = 4, maxC = 8 , ch = 'c', pwd = "bvxgnmvczbsjvtc" }
  , Pwd { minC = 11, maxC = 18 , ch = 'g', pwd = "gggggggggzzgggggggp" }
  , Pwd { minC = 8, maxC = 13 , ch = 'p', pwd = "pppppwpdppppppp" }
  , Pwd { minC = 14, maxC = 15 , ch = 't', pwd = "tttttgttttttttj" }
  , Pwd { minC = 14, maxC = 17 , ch = 'h', pwd = "hhhdnhhhhhhhhbhhg" }
  , Pwd { minC = 3, maxC = 5 , ch = 'm', pwd = "mmmmm" }
  , Pwd { minC = 1, maxC = 8 , ch = 'n', pwd = "znnnnnnhn" }
  , Pwd { minC = 2, maxC = 5 , ch = 'l', pwd = "qwvchzxlrlrlpldl" }
  , Pwd { minC = 17, maxC = 18 , ch = 'j', pwd = "jjjjjjjjjjjjjjjjjmj" }
  , Pwd { minC = 7, maxC = 18 , ch = 's', pwd = "sksssssssstsssshsg" }
  , Pwd { minC = 4, maxC = 5 , ch = 'k', pwd = "kbqks" }
  , Pwd { minC = 6, maxC = 8 , ch = 'q', pwd = "qqqqklcjm" }
  , Pwd { minC = 8, maxC = 17 , ch = 'x', pwd = "tjdsxwtxwxcjtzxfxgkt" }
  , Pwd { minC = 5, maxC = 8 , ch = 'w', pwd = "qwxwvwcwvzlvrwwww" }
  , Pwd { minC = 16, maxC = 18 , ch = 'f', pwd = "fffffffffffffftfffff" }
  , Pwd { minC = 3, maxC = 12 , ch = 'z', pwd = "zzzzzzzzzzzfzzzz" }
  , Pwd { minC = 10, maxC = 13 , ch = 'm', pwd = "mmmmqmmmvmmmx" }
  , Pwd { minC = 4, maxC = 7 , ch = 'z', pwd = "zkjzvpf" }
  , Pwd { minC = 11, maxC = 13 , ch = 'p', pwd = "pzqpppppppgpt" }
  , Pwd { minC = 11, maxC = 12 , ch = 'c', pwd = "cccccwfccccccz" }
  , Pwd { minC = 3, maxC = 4 , ch = 's', pwd = "ssxsss" }
  , Pwd { minC = 8, maxC = 9 , ch = 'j', pwd = "bsjjjjjpxjjjj" }
  , Pwd { minC = 2, maxC = 7 , ch = 'x', pwd = "cxkbqkf" }
  , Pwd { minC = 7, maxC = 18 , ch = 'x', pwd = "vmrsdvxxpbjrxbnxqxxg" }
  , Pwd { minC = 8, maxC = 11 , ch = 'd', pwd = "nwzdcqvddfd" }
  , Pwd { minC = 7, maxC = 11 , ch = 'h', pwd = "hhhhhhlhbhhh" }
  , Pwd { minC = 9, maxC = 10 , ch = 'f', pwd = "fhlmjqfzfq" }
  , Pwd { minC = 13, maxC = 15 , ch = 'p', pwd = "jcfprqlvrnfnfnp" }
  , Pwd { minC = 2, maxC = 3 , ch = 'b', pwd = "gblb" }
  , Pwd { minC = 5, maxC = 7 , ch = 's', pwd = "jssssqz" }
  , Pwd { minC = 1, maxC = 18 , ch = 'c', pwd = "ccccccccccccccccczc" }
  , Pwd { minC = 10, maxC = 15 , ch = 'x', pwd = "xxxxxxxxxwxxxxxg" }
  , Pwd { minC = 6, maxC = 7 , ch = 'w', pwd = "jswwwwdcw" }
  , Pwd { minC = 4, maxC = 10 , ch = 'q', pwd = "bqtxmcgxnjnkvq" }
  , Pwd { minC = 1, maxC = 2 , ch = 'c', pwd = "ccccc" }
  , Pwd { minC = 10, maxC = 12 , ch = 'h', pwd = "hhhlhhhhjkhsh" }
  , Pwd { minC = 3, maxC = 4 , ch = 'w', pwd = "hwgwxd" }
  , Pwd { minC = 17, maxC = 19 , ch = 'j', pwd = "jjjjjjjjjjjjjjjjdjpj" }
  , Pwd { minC = 1, maxC = 4 , ch = 'd', pwd = "dddt" }
  , Pwd { minC = 7, maxC = 8 , ch = 'z', pwd = "zzzzzzlhz" }
  , Pwd { minC = 13, maxC = 16 , ch = 'z', pwd = "zzzzzdzzzzzzzzzpzzz" }
  , Pwd { minC = 4, maxC = 10 , ch = 'd', pwd = "dgdzdddddddd" }
  , Pwd { minC = 4, maxC = 7 , ch = 'l', pwd = "llclxltlpqh" }
  , Pwd { minC = 1, maxC = 4 , ch = 'x', pwd = "hxxxx" }
  , Pwd { minC = 5, maxC = 7 , ch = 'n', pwd = "vnnnnnndxn" }
  , Pwd { minC = 10, maxC = 11 , ch = 'n', pwd = "nnnnnnnnngg" }
  , Pwd { minC = 5, maxC = 12 , ch = 'k', pwd = "bkcdkpjrpkkv" }
  , Pwd { minC = 6, maxC = 8 , ch = 'j', pwd = "lsjhjjqjcx" }
  , Pwd { minC = 7, maxC = 10 , ch = 't', pwd = "ttttfttttt" }
  , Pwd { minC = 17, maxC = 19 , ch = 'n', pwd = "nnwnnnnnnnnnnnjndznf" }
  , Pwd { minC = 1, maxC = 4 , ch = 'v', pwd = "vvvv" }
  , Pwd { minC = 14, maxC = 18 , ch = 'x', pwd = "xxxxxxxxxxxxxnxxxx" }
  , Pwd { minC = 3, maxC = 5 , ch = 'x', pwd = "kxjjx" }
  , Pwd { minC = 3, maxC = 8 , ch = 'k', pwd = "kkrkkkkskkkkkkk" }
  , Pwd { minC = 8, maxC = 11 , ch = 'h', pwd = "hhhhhhhhhhlhhnjh" }
  , Pwd { minC = 4, maxC = 5 , ch = 'x', pwd = "nxxxnz" }
  , Pwd { minC = 7, maxC = 10 , ch = 'z', pwd = "zzzzzzzbzq" }
  , Pwd { minC = 7, maxC = 13 , ch = 'b', pwd = "dvbsbbbbbbbkcbb" }
  , Pwd { minC = 3, maxC = 5 , ch = 'k', pwd = "drkrkpnhkpjhkk" }
  , Pwd { minC = 8, maxC = 9 , ch = 'w', pwd = "wrwwwwwwf" }
  , Pwd { minC = 3, maxC = 4 , ch = 'x', pwd = "kxxtwx" }
  , Pwd { minC = 5, maxC = 17 , ch = 'n', pwd = "nnbnnnlnnnnnnqnnn" }
  , Pwd { minC = 11, maxC = 14 , ch = 'k', pwd = "kkkkqkkbkklkkkkkkkkk" }
  , Pwd { minC = 4, maxC = 7 , ch = 'q', pwd = "qqjjqqqqqqq" }
  , Pwd { minC = 3, maxC = 4 , ch = 'k', pwd = "gkkkxlx" }
  , Pwd { minC = 11, maxC = 17 , ch = 's', pwd = "ssssqssssjrsmgssstgs" }
  , Pwd { minC = 6, maxC = 17 , ch = 'n', pwd = "dntjvnhjgrbtcnnmkdc" }
  , Pwd { minC = 1, maxC = 5 , ch = 'l', pwd = "hrqqlqpdlmbjlllmfjqz" }
  , Pwd { minC = 1, maxC = 5 , ch = 'k', pwd = "kkkvk" }
  , Pwd { minC = 9, maxC = 15 , ch = 'z', pwd = "zmzzzjzxmzzzbzv" }
  , Pwd { minC = 1, maxC = 2 , ch = 's', pwd = "rsssxzss" }
  , Pwd { minC = 1, maxC = 4 , ch = 'f', pwd = "fdfc" }
  , Pwd { minC = 1, maxC = 7 , ch = 't', pwd = "ntttttttttt" }
  , Pwd { minC = 10, maxC = 12 , ch = 't', pwd = "mtttzttwtttkstjtztt" }
  , Pwd { minC = 9, maxC = 15 , ch = 'q', pwd = "qlqqqbqqqqqqqqq" }
  , Pwd { minC = 4, maxC = 5 , ch = 'f', pwd = "jwfff" }
  , Pwd { minC = 5, maxC = 6 , ch = 'p', pwd = "ppwppvppp" }
  , Pwd { minC = 12, maxC = 14 , ch = 'p', pwd = "ppppppppppplppp" }
  , Pwd { minC = 2, maxC = 8 , ch = 'x', pwd = "wxbngjrxzx" }
  , Pwd { minC = 1, maxC = 2 , ch = 'h', pwd = "hlhlg" }
  , Pwd { minC = 9, maxC = 10 , ch = 'b', pwd = "bbbbbdbbbqb" }
  , Pwd { minC = 6, maxC = 15 , ch = 'w', pwd = "wwwwwwwcwwwwwwww" }
  , Pwd { minC = 2, maxC = 7 , ch = 'd', pwd = "sgcfddnqmjthdphl" }
  , Pwd { minC = 7, maxC = 9 , ch = 'm', pwd = "zqrwxkmjr" }
  , Pwd { minC = 5, maxC = 7 , ch = 'f', pwd = "qklfrzfgffff" }
  , Pwd { minC = 14, maxC = 15 , ch = 'n', pwd = "lnnnnnnnnnnnnnnn" }
  , Pwd { minC = 2, maxC = 11 , ch = 'q', pwd = "gqqlcqjlqrsbqkqqq" }
  , Pwd { minC = 7, maxC = 8 , ch = 'x', pwd = "xxxxxnlx" }
  , Pwd { minC = 2, maxC = 9 , ch = 'v', pwd = "xvvqbvfkwd" }
  , Pwd { minC = 10, maxC = 12 , ch = 'z', pwd = "rmvxznxnszkzdb" }
  , Pwd { minC = 2, maxC = 3 , ch = 'q', pwd = "qkqq" }
  , Pwd { minC = 2, maxC = 6 , ch = 'n', pwd = "nnqqgv" }
  , Pwd { minC = 4, maxC = 6 , ch = 'd', pwd = "dddddc" }
  , Pwd { minC = 8, maxC = 9 , ch = 'z', pwd = "zzzzwzjzz" }
  , Pwd { minC = 1, maxC = 14 , ch = 'q', pwd = "wxqnqqqqqqtqqq" }
  , Pwd { minC = 1, maxC = 5 , ch = 'g', pwd = "grgtggnh" }
  , Pwd { minC = 4, maxC = 6 , ch = 'x', pwd = "mbtxxxxxxtm" }
  , Pwd { minC = 3, maxC = 7 , ch = 'w', pwd = "wwtwwww" }
  , Pwd { minC = 4, maxC = 6 , ch = 'h', pwd = "phchhbxf" }
  , Pwd { minC = 4, maxC = 6 , ch = 'n', pwd = "npznhtxf" }
  , Pwd { minC = 14, maxC = 20 , ch = 'v', pwd = "vkpjvvbrvvvfvzvvvcxv" }
  , Pwd { minC = 17, maxC = 18 , ch = 'm', pwd = "rmccmmmmvmkmnmqtmz" }
  , Pwd { minC = 4, maxC = 9 , ch = 'n', pwd = "nnsnxnfbjnjnnnkn" }
  , Pwd { minC = 8, maxC = 10 , ch = 'c', pwd = "ccqclccvcccc" }
  , Pwd { minC = 1, maxC = 12 , ch = 'b', pwd = "blbhbbbbbbbbbbgbbbb" }
  , Pwd { minC = 4, maxC = 8 , ch = 'v', pwd = "vvvbvvvgv" }
  , Pwd { minC = 4, maxC = 6 , ch = 'm', pwd = "mdnmmmgrsqjjbctjvhm" }
  , Pwd { minC = 6, maxC = 9 , ch = 'r', pwd = "rlrrgrrrhr" }
  , Pwd { minC = 4, maxC = 6 , ch = 'q', pwd = "qqqjnq" }
  , Pwd { minC = 8, maxC = 9 , ch = 'g', pwd = "spqxllrngwkjgpzpg" }
  , Pwd { minC = 6, maxC = 9 , ch = 'm', pwd = "zbsggmvzsmpcm" }
  , Pwd { minC = 3, maxC = 9 , ch = 's', pwd = "xssmzstbsrfz" }
  , Pwd { minC = 4, maxC = 11 , ch = 'c', pwd = "cxcrrccccrcncc" }
  , Pwd { minC = 3, maxC = 4 , ch = 'p', pwd = "ppqb" }
  , Pwd { minC = 5, maxC = 8 , ch = 'f', pwd = "vcfflfflmf" }
  , Pwd { minC = 9, maxC = 13 , ch = 'b', pwd = "bbbpwbjbkbhbbktz" }
  , Pwd { minC = 4, maxC = 9 , ch = 'p', pwd = "ppppppmpps" }
  , Pwd { minC = 7, maxC = 17 , ch = 's', pwd = "ssssksrvssnsbsssrxsm" }
  , Pwd { minC = 10, maxC = 12 , ch = 'm', pwd = "mmmmmmmmmmmsmgmm" }
  , Pwd { minC = 6, maxC = 13 , ch = 'x', pwd = "xwxxxxxxxxxxm" }
  , Pwd { minC = 9, maxC = 10 , ch = 't', pwd = "rrthttjtttwlvpttgttt" }
  , Pwd { minC = 6, maxC = 10 , ch = 'z', pwd = "vzklxxzvwgzt" }
  , Pwd { minC = 2, maxC = 4 , ch = 'v', pwd = "vvvk" }
  , Pwd { minC = 5, maxC = 8 , ch = 'h', pwd = "twhghhhw" }
  , Pwd { minC = 7, maxC = 8 , ch = 'n', pwd = "nnwnnknrn" }
  , Pwd { minC = 2, maxC = 4 , ch = 'm', pwd = "mmmmm" }
  , Pwd { minC = 3, maxC = 7 , ch = 'r', pwd = "srxrrmrwrrhrg" }
  , Pwd { minC = 5, maxC = 6 , ch = 'x', pwd = "xxxxxh" }
  , Pwd { minC = 5, maxC = 6 , ch = 'x', pwd = "xxxxxtx" }
  , Pwd { minC = 5, maxC = 13 , ch = 'd', pwd = "ddddddddddddndddd" }
  , Pwd { minC = 15, maxC = 16 , ch = 'c', pwd = "drfrpmbhcncvmxnk" }
  , Pwd { minC = 14, maxC = 15 , ch = 'r', pwd = "rrrrrrrrrrrrrrk" }
  , Pwd { minC = 4, maxC = 6 , ch = 'z', pwd = "qmlsgz" }
  , Pwd { minC = 9, maxC = 10 , ch = 'x', pwd = "xxxpnxrxxl" }
  , Pwd { minC = 3, maxC = 6 , ch = 'h', pwd = "hhhhwfhh" }
  , Pwd { minC = 3, maxC = 8 , ch = 'b', pwd = "jvpscbzbvb" }
  , Pwd { minC = 9, maxC = 12 , ch = 'j', pwd = "jjjjjjjjfjjj" }
  , Pwd { minC = 1, maxC = 2 , ch = 'n', pwd = "hwnn" }
  , Pwd { minC = 3, maxC = 9 , ch = 'l', pwd = "lpgmzxcwlpsp" }
  , Pwd { minC = 2, maxC = 7 , ch = 'k', pwd = "zkbnlwlpk" }
  , Pwd { minC = 2, maxC = 12 , ch = 't', pwd = "tttttttttttttt" }
  , Pwd { minC = 5, maxC = 14 , ch = 'h', pwd = "rhjchxhlfjhxfhhb" }
  , Pwd { minC = 1, maxC = 4 , ch = 'p', pwd = "pbstdbpctfdzxzh" }
  , Pwd { minC = 9, maxC = 14 , ch = 'k', pwd = "swkkkkckqkkrqlkkrtk" }
  , Pwd { minC = 5, maxC = 6 , ch = 'v', pwd = "vcvkxvfvrmvvv" }
  , Pwd { minC = 14, maxC = 17 , ch = 'n', pwd = "nnnnnnnnnnnnnnnns" }
  , Pwd { minC = 9, maxC = 13 , ch = 'd', pwd = "dbdjdhdhrddgmk" }
  , Pwd { minC = 5, maxC = 6 , ch = 'c', pwd = "cvzcclcccdf" }
  , Pwd { minC = 16, maxC = 18 , ch = 'x', pwd = "xxxxxxxxxxxxxxxxxxx" }
  , Pwd { minC = 15, maxC = 16 , ch = 'v', pwd = "vvvvvvvvvvvvvvfv" }
  , Pwd { minC = 3, maxC = 6 , ch = 'g', pwd = "jggwkcdpmmttl" }
  , Pwd { minC = 18, maxC = 19 , ch = 'g', pwd = "gggslcgggtggggggxgxd" }
  , Pwd { minC = 7, maxC = 10 , ch = 'r', pwd = "rrrvrrjrrrrrr" }
  , Pwd { minC = 7, maxC = 8 , ch = 'f', pwd = "xzmwmgfkh" }
  , Pwd { minC = 2, maxC = 4 , ch = 'g', pwd = "gcgvg" }
  , Pwd { minC = 5, maxC = 7 , ch = 'k', pwd = "qkknzkfncgkckkj" }
  , Pwd { minC = 8, maxC = 10 , ch = 'q', pwd = "qxgvffbqgq" }
  , Pwd { minC = 5, maxC = 7 , ch = 'd', pwd = "slfqbddnrvj" }
  , Pwd { minC = 8, maxC = 11 , ch = 'k', pwd = "xtfkkwnccck" }
  , Pwd { minC = 3, maxC = 4 , ch = 's', pwd = "jsrs" }
  , Pwd { minC = 3, maxC = 6 , ch = 'm', pwd = "mmdmkmwmmmnd" }
  , Pwd { minC = 6, maxC = 7 , ch = 'q', pwd = "gxbthqc" }
  , Pwd { minC = 6, maxC = 7 , ch = 'v', pwd = "vvvvvqv" }
  , Pwd { minC = 7, maxC = 14 , ch = 'n', pwd = "nxnqnnqnqnnnnnn" }
  , Pwd { minC = 8, maxC = 12 , ch = 'd', pwd = "chkdcslxddddd" }
  , Pwd { minC = 8, maxC = 11 , ch = 'g', pwd = "cgwlgszgfnk" }
  , Pwd { minC = 12, maxC = 13 , ch = 'b', pwd = "bbbbbbbbbbbjc" }
  , Pwd { minC = 7, maxC = 9 , ch = 'w', pwd = "wwwwtwwqdw" }
  , Pwd { minC = 14, maxC = 15 , ch = 'q', pwd = "qqqqqqqqqqqqqlq" }
  , Pwd { minC = 8, maxC = 11 , ch = 'q', pwd = "rhmqdzslbgqwq" }
  , Pwd { minC = 4, maxC = 5 , ch = 'k', pwd = "khkxrqxwb" }
  , Pwd { minC = 2, maxC = 6 , ch = 'l', pwd = "lskblllkqxdllmhl" }
  , Pwd { minC = 2, maxC = 9 , ch = 's', pwd = "xwxncpjgch" }
  , Pwd { minC = 8, maxC = 14 , ch = 'x', pwd = "vxxxxxxhcxxxdxxm" }
  , Pwd { minC = 3, maxC = 11 , ch = 'g', pwd = "gggwgggggggggg" }
  , Pwd { minC = 9, maxC = 11 , ch = 'b', pwd = "fbbfdmbbbbjbstbb" }
  , Pwd { minC = 5, maxC = 13 , ch = 'z', pwd = "zzzzxnzzzzzzzgz" }
  , Pwd { minC = 1, maxC = 10 , ch = 'b', pwd = "bnsbgsnrbb" }
  , Pwd { minC = 3, maxC = 6 , ch = 'w', pwd = "zxtfmwndwnwkj" }
  , Pwd { minC = 2, maxC = 4 , ch = 's', pwd = "smss" }
  , Pwd { minC = 4, maxC = 5 , ch = 'q', pwd = "qjqqz" }
  , Pwd { minC = 12, maxC = 15 , ch = 'b', pwd = "kbbbbbbbxbbhbbj" }
  , Pwd { minC = 3, maxC = 4 , ch = 'd', pwd = "dhkd" }
  , Pwd { minC = 5, maxC = 6 , ch = 'k', pwd = "pkbkkp" }
  , Pwd { minC = 2, maxC = 4 , ch = 'p', pwd = "wppkz" }
  , Pwd { minC = 2, maxC = 6 , ch = 'd', pwd = "dnddgd" }
  , Pwd { minC = 7, maxC = 10 , ch = 'j', pwd = "jdwrhhjszjbkmfphj" }
  , Pwd { minC = 1, maxC = 3 , ch = 'b', pwd = "vkcbb" }
  , Pwd { minC = 7, maxC = 8 , ch = 'f', pwd = "ffffffdf" }
  , Pwd { minC = 11, maxC = 13 , ch = 't', pwd = "ttttttttttttl" }
  , Pwd { minC = 14, maxC = 18 , ch = 'x', pwd = "xvxxfxxxxrxxxgxxxrx" }
  , Pwd { minC = 8, maxC = 10 , ch = 'k', pwd = "gtkbkksnkskkrkkk" }
  , Pwd { minC = 2, maxC = 4 , ch = 'h', pwd = "hnhh" }
  , Pwd { minC = 10, maxC = 13 , ch = 'm', pwd = "vmmwpmlmnckmcmm" }
  , Pwd { minC = 1, maxC = 2 , ch = 'z', pwd = "zzzsz" }
  , Pwd { minC = 4, maxC = 5 , ch = 'p', pwd = "pppbf" }
  , Pwd { minC = 2, maxC = 4 , ch = 'q', pwd = "pwdbsxlrqmhhtccl" }
  , Pwd { minC = 9, maxC = 11 , ch = 'f', pwd = "fffhffffvffvfq" }
  , Pwd { minC = 8, maxC = 9 , ch = 'x', pwd = "xxrxxxxsx" }
  , Pwd { minC = 8, maxC = 14 , ch = 'z', pwd = "zzzzzzzzzzmzzzz" }
  , Pwd { minC = 9, maxC = 11 , ch = 'j', pwd = "jjjjqjjpjjwj" }
  , Pwd { minC = 3, maxC = 4 , ch = 's', pwd = "sskss" }
  , Pwd { minC = 8, maxC = 12 , ch = 's', pwd = "tlcssmclnvgstg" }
  , Pwd { minC = 11, maxC = 12 , ch = 'v', pwd = "vvdnvmvsvvkx" }
  , Pwd { minC = 4, maxC = 5 , ch = 'c', pwd = "ccccbcc" }
  , Pwd { minC = 1, maxC = 2 , ch = 'd', pwd = "ddthwdk" }
  , Pwd { minC = 10, maxC = 13 , ch = 'n', pwd = "nnnnfnnnnpncnm" }
  , Pwd { minC = 7, maxC = 8 , ch = 'z', pwd = "zzzzvzbz" }
  , Pwd { minC = 2, maxC = 3 , ch = 'n', pwd = "nnsqnrnnnnnltn" }
  , Pwd { minC = 4, maxC = 5 , ch = 'q', pwd = "qqqmq" }
  , Pwd { minC = 6, maxC = 9 , ch = 's', pwd = "ssnsssssksc" }
  , Pwd { minC = 9, maxC = 11 , ch = 'r', pwd = "rrrfrrrrhrrr" }
  , Pwd { minC = 3, maxC = 4 , ch = 'd', pwd = "tzdd" }
  , Pwd { minC = 3, maxC = 6 , ch = 'c', pwd = "cccccmcc" }
  , Pwd { minC = 7, maxC = 8 , ch = 'q', pwd = "qqqqtmsqqqqq" }
  , Pwd { minC = 17, maxC = 18 , ch = 'z', pwd = "zwkzbhqnhznzlkqxnz" }
  , Pwd { minC = 4, maxC = 7 , ch = 'm', pwd = "hfvdmmnszdmb" }
  , Pwd { minC = 14, maxC = 17 , ch = 'z', pwd = "zzzzzzzzzzzzzzzzjzz" }
  , Pwd { minC = 12, maxC = 14 , ch = 'k', pwd = "kkkkqkfkkkkjkz" }
  , Pwd { minC = 1, maxC = 3 , ch = 'z', pwd = "zzdzh" }
  , Pwd { minC = 2, maxC = 7 , ch = 'v', pwd = "vvvvnvr" }
  , Pwd { minC = 14, maxC = 16 , ch = 'j', pwd = "jjjjjjmjnjxjjtjjjwj" }
  , Pwd { minC = 15, maxC = 18 , ch = 'h', pwd = "hhhhwhhqhhtfhhhhhzhh" }
  , Pwd { minC = 1, maxC = 2 , ch = 'z', pwd = "dzznmxzt" }
  , Pwd { minC = 5, maxC = 6 , ch = 'c', pwd = "cccpkc" }
  , Pwd { minC = 6, maxC = 10 , ch = 'z', pwd = "trwqgzmwtvbgnvjkxz" }
  , Pwd { minC = 3, maxC = 4 , ch = 'w', pwd = "twwjwg" }
  , Pwd { minC = 6, maxC = 10 , ch = 'w', pwd = "nwwcxwjschxpjkrqwvw" }
  , Pwd { minC = 9, maxC = 10 , ch = 'z', pwd = "kzzfzzzzzhlzzg" }
  , Pwd { minC = 6, maxC = 7 , ch = 'r', pwd = "rrzhqnnrrrhk" }
  , Pwd { minC = 9, maxC = 11 , ch = 'k', pwd = "kkklkzkgkrkj" }
  , Pwd { minC = 11, maxC = 16 , ch = 'd', pwd = "ddddddsrdddpbdldrb" }
  , Pwd { minC = 6, maxC = 9 , ch = 'v', pwd = "njfrfxbqvv" }
  , Pwd { minC = 3, maxC = 4 , ch = 'j', pwd = "jjjd" }
  , Pwd { minC = 3, maxC = 4 , ch = 'q', pwd = "qgqq" }
  , Pwd { minC = 4, maxC = 15 , ch = 'h', pwd = "hhhtthhhhhhhhhhhh" }
  , Pwd { minC = 3, maxC = 11 , ch = 'b', pwd = "bbbcnzglwcbqxgwvbc" }
  , Pwd { minC = 2, maxC = 3 , ch = 'b', pwd = "nbhbrkkzbs" }
  , Pwd { minC = 4, maxC = 5 , ch = 'p', pwd = "ppppk" }
  , Pwd { minC = 2, maxC = 5 , ch = 'q', pwd = "jqkzqrzqbtkcqgb" }
  , Pwd { minC = 6, maxC = 7 , ch = 's', pwd = "sssssqm" }
  , Pwd { minC = 1, maxC = 5 , ch = 'r', pwd = "rrrrr" }
  , Pwd { minC = 3, maxC = 4 , ch = 'w', pwd = "wwwgt" }
  , Pwd { minC = 2, maxC = 8 , ch = 'x', pwd = "xxxxxxqx" }
  , Pwd { minC = 9, maxC = 10 , ch = 'c', pwd = "ccfccccwcc" }
  , Pwd { minC = 2, maxC = 10 , ch = 'r', pwd = "crmkxbcrrkr" }
  , Pwd { minC = 7, maxC = 16 , ch = 'c', pwd = "cmmfkhclcwqjcqsmccn" }
  , Pwd { minC = 7, maxC = 14 , ch = 'p', pwd = "ppgppppppppppqppppp" }
  , Pwd { minC = 1, maxC = 3 , ch = 's', pwd = "sshs" }
  , Pwd { minC = 1, maxC = 3 , ch = 'd', pwd = "lfdd" }
  , Pwd { minC = 5, maxC = 14 , ch = 'n', pwd = "fkxsnvxclfnklbqrknvd" }
  , Pwd { minC = 15, maxC = 17 , ch = 'j', pwd = "jwjjjjjjjzjjjjjjpj" }
  , Pwd { minC = 4, maxC = 7 , ch = 'l', pwd = "lllljnlt" }
  , Pwd { minC = 5, maxC = 8 , ch = 'c', pwd = "pczkvcsqpfzcw" }
  , Pwd { minC = 3, maxC = 14 , ch = 'q', pwd = "xkqqsvcqdqqqjscfd" }
  , Pwd { minC = 7, maxC = 11 , ch = 'm', pwd = "rmhmmmmmmmjmm" }
  , Pwd { minC = 10, maxC = 13 , ch = 'x', pwd = "xxxxxxxxxhxxxxx" }
  , Pwd { minC = 1, maxC = 4 , ch = 'm', pwd = "mmmmm" }
  , Pwd { minC = 1, maxC = 4 , ch = 'r', pwd = "dmrrl" }
  , Pwd { minC = 10, maxC = 11 , ch = 's', pwd = "sssssslssgg" }
  , Pwd { minC = 9, maxC = 10 , ch = 'g', pwd = "rtksgmrpbl" }
  , Pwd { minC = 4, maxC = 10 , ch = 't', pwd = "wtfttttttbmntsth" }
  , Pwd { minC = 8, maxC = 18 , ch = 'k', pwd = "vwstrvjbjttzbrtghwk" }
  , Pwd { minC = 9, maxC = 11 , ch = 's', pwd = "ssdslssssss" }
  , Pwd { minC = 10, maxC = 13 , ch = 's', pwd = "pssssssfcnjcs" }
  , Pwd { minC = 2, maxC = 17 , ch = 'l', pwd = "wpltglllsslllwlslrpc" }
  , Pwd { minC = 13, maxC = 15 , ch = 'g', pwd = "gglggglgggvgwgzgggg" }
  , Pwd { minC = 4, maxC = 6 , ch = 'v', pwd = "qqvvvvvlbzdv" }
  , Pwd { minC = 4, maxC = 5 , ch = 'j', pwd = "jjqdvt" }
  , Pwd { minC = 2, maxC = 9 , ch = 'n', pwd = "nnnnfvxnpvfjnnbg" }
  , Pwd { minC = 2, maxC = 9 , ch = 'c', pwd = "pgctwtlccvl" }
  , Pwd { minC = 4, maxC = 6 , ch = 'n', pwd = "nnnqncnnn" }
  , Pwd { minC = 2, maxC = 5 , ch = 'l', pwd = "lzllllnll" }
  , Pwd { minC = 6, maxC = 10 , ch = 'k', pwd = "zjkkvkkzwkk" }
  , Pwd { minC = 3, maxC = 4 , ch = 'h', pwd = "hhhkh" }
  , Pwd { minC = 3, maxC = 15 , ch = 'k', pwd = "kkkgkkkxkkknkkv" }
  , Pwd { minC = 4, maxC = 7 , ch = 'k', pwd = "skkknxdf" }
  , Pwd { minC = 4, maxC = 8 , ch = 'h', pwd = "hhhhzhkdj" }
  , Pwd { minC = 9, maxC = 11 , ch = 'j', pwd = "jjjjjjjjjjsk" }
  , Pwd { minC = 3, maxC = 6 , ch = 's', pwd = "qswngs" }
  , Pwd { minC = 3, maxC = 7 , ch = 'v', pwd = "vvcvvvvvv" }
  , Pwd { minC = 11, maxC = 12 , ch = 's', pwd = "ggcxrkcsntpsf" }
  , Pwd { minC = 3, maxC = 4 , ch = 'v', pwd = "hvvv" }
  , Pwd { minC = 15, maxC = 16 , ch = 't', pwd = "tttfttftttfttttkttt" }
  , Pwd { minC = 8, maxC = 13 , ch = 'b', pwd = "bbbbbbqgbrbcbqbb" }
  , Pwd { minC = 9, maxC = 12 , ch = 's', pwd = "cstnslsssjsv" }
  , Pwd { minC = 3, maxC = 13 , ch = 'j', pwd = "kwkjmmqtpcjcjhdllwjj" }
  , Pwd { minC = 2, maxC = 6 , ch = 'r', pwd = "rrrrrn" }
  , Pwd { minC = 10, maxC = 11 , ch = 's', pwd = "bsssssstsssss" }
  , Pwd { minC = 1, maxC = 6 , ch = 'f', pwd = "cgggvn" }
  , Pwd { minC = 3, maxC = 10 , ch = 'l', pwd = "hblknspmlx" }
  , Pwd { minC = 2, maxC = 3 , ch = 'h', pwd = "hthhhs" }
  , Pwd { minC = 3, maxC = 5 , ch = 'n', pwd = "nnbwn" }
  , Pwd { minC = 1, maxC = 3 , ch = 'z', pwd = "nzgzzz" }
  , Pwd { minC = 16, maxC = 19 , ch = 'p', pwd = "pppppppppqppppppppqp" }
  , Pwd { minC = 5, maxC = 11 , ch = 'd', pwd = "ddddntddgdd" }
  , Pwd { minC = 6, maxC = 7 , ch = 's', pwd = "ssssswk" }
  , Pwd { minC = 1, maxC = 7 , ch = 'r', pwd = "lrrkrqrwbkk" }
  , Pwd { minC = 2, maxC = 9 , ch = 'z', pwd = "cwzthgjzzgzzhzz" }
  , Pwd { minC = 3, maxC = 4 , ch = 'c', pwd = "cxxt" }
  , Pwd { minC = 5, maxC = 13 , ch = 'c', pwd = "jczpcmcccccccjpc" }
  , Pwd { minC = 7, maxC = 8 , ch = 'l', pwd = "llllllgf" }
  , Pwd { minC = 3, maxC = 11 , ch = 'q', pwd = "rqkxqckgqqqqb" }
  , Pwd { minC = 2, maxC = 14 , ch = 'r', pwd = "mhlbmsrsgrwrtrbrpt" }
  , Pwd { minC = 2, maxC = 10 , ch = 'v', pwd = "tvnxllwvhdkcjsvxlztx" }
  , Pwd { minC = 2, maxC = 3 , ch = 'q', pwd = "nwqqwfqlq" }
  , Pwd { minC = 16, maxC = 18 , ch = 'k', pwd = "bdkkktkkkkkkkkkqjq" }
  , Pwd { minC = 8, maxC = 17 , ch = 'k', pwd = "pkjckwmzqkkvqqshks" }
  , Pwd { minC = 6, maxC = 7 , ch = 'f', pwd = "fffffbff" }
  , Pwd { minC = 3, maxC = 7 , ch = 'p', pwd = "pppphpp" }
  , Pwd { minC = 6, maxC = 8 , ch = 'w', pwd = "wrwcwwjswnwwwp" }
  , Pwd { minC = 3, maxC = 4 , ch = 'h', pwd = "hhfh" }
  , Pwd { minC = 2, maxC = 5 , ch = 'h', pwd = "hhhrsc" }
  , Pwd { minC = 3, maxC = 19 , ch = 'b', pwd = "txxmgxhnbqhtjhjfvdbb" }
  , Pwd { minC = 14, maxC = 20 , ch = 'w', pwd = "wwwwwwpwqnwwkwwwwwwn" }
  , Pwd { minC = 5, maxC = 6 , ch = 'z', pwd = "zzzzvz" }
  , Pwd { minC = 2, maxC = 5 , ch = 'x', pwd = "rxxllbfhnvxx" }
  , Pwd { minC = 15, maxC = 17 , ch = 'f', pwd = "fwtfjjfffwfffffph" }
  , Pwd { minC = 1, maxC = 6 , ch = 'm', pwd = "msmmmwmsmmmm" }
  , Pwd { minC = 6, maxC = 11 , ch = 'f', pwd = "mdtdmfhpscfmrm" }
  , Pwd { minC = 1, maxC = 16 , ch = 'l', pwd = "zmlxxnlzzbhfscll" }
  , Pwd { minC = 14, maxC = 15 , ch = 'x', pwd = "xxxxxxsxxxxxxxt" }
  , Pwd { minC = 7, maxC = 10 , ch = 'q', pwd = "qqqbpqqqhdq" }
  , Pwd { minC = 5, maxC = 8 , ch = 'v', pwd = "vvbrtvwvvvlvvsv" }
  , Pwd { minC = 6, maxC = 7 , ch = 'x', pwd = "xwfzsjxxxxzpxvsx" }
  , Pwd { minC = 7, maxC = 10 , ch = 'l', pwd = "lllllldmll" }
  , Pwd { minC = 10, maxC = 11 , ch = 'c', pwd = "cctccccccdw" }
  , Pwd { minC = 3, maxC = 6 , ch = 'g', pwd = "ggppjgg" }
  , Pwd { minC = 16, maxC = 18 , ch = 'c', pwd = "cfcmcczcvwccccgccccc" }
  , Pwd { minC = 7, maxC = 9 , ch = 'v', pwd = "vxdvzvvvchbvvvq" }
  , Pwd { minC = 11, maxC = 18 , ch = 't', pwd = "btnttrttqbtgtxttstrc" }
  , Pwd { minC = 8, maxC = 10 , ch = 'p', pwd = "hppppbptppsp" }
  , Pwd { minC = 9, maxC = 10 , ch = 'g', pwd = "gtsgglgggtgg" }
  , Pwd { minC = 13, maxC = 20 , ch = 'f', pwd = "ffpsfffffffffffffffg" }
  , Pwd { minC = 12, maxC = 19 , ch = 'm', pwd = "rmpmmdvzmtmmbfmtxwm" }
  , Pwd { minC = 1, maxC = 7 , ch = 'g', pwd = "xgggggxgg" }
  , Pwd { minC = 1, maxC = 8 , ch = 'w', pwd = "wsnkwcww" }
  , Pwd { minC = 2, maxC = 3 , ch = 'z', pwd = "zmzgxp" }
  , Pwd { minC = 9, maxC = 11 , ch = 'w', pwd = "wwwnwwwwwkww" }
  , Pwd { minC = 5, maxC = 6 , ch = 'w', pwd = "wwwwrw" }
  , Pwd { minC = 4, maxC = 5 , ch = 's', pwd = "prxsnscsm" }
  , Pwd { minC = 5, maxC = 6 , ch = 'n', pwd = "nnnndn" }
  , Pwd { minC = 6, maxC = 14 , ch = 'g', pwd = "gfqgggwggjlswdg" }
  , Pwd { minC = 1, maxC = 3 , ch = 't', pwd = "tvtqmtth" }
  , Pwd { minC = 9, maxC = 10 , ch = 'v', pwd = "vvvvvvvvvtvvv" }
  , Pwd { minC = 3, maxC = 4 , ch = 'd', pwd = "dbvfdw" }
  , Pwd { minC = 10, maxC = 11 , ch = 'x', pwd = "nxhxxnxxxvx" }
  , Pwd { minC = 19, maxC = 20 , ch = 'c', pwd = "rcchbchcsjghmnjbgpcc" }
  , Pwd { minC = 7, maxC = 8 , ch = 'n', pwd = "mxtnnkxcnhnnjknptn" }
  , Pwd { minC = 3, maxC = 8 , ch = 'k', pwd = "knjxpwkkzkmzkwfknvzg" }
  , Pwd { minC = 9, maxC = 10 , ch = 'z', pwd = "zzzzlznzztzzz" }
  , Pwd { minC = 1, maxC = 2 , ch = 'k', pwd = "pxkk" }
  , Pwd { minC = 2, maxC = 3 , ch = 'k', pwd = "spkgwkpmns" }
  , Pwd { minC = 12, maxC = 13 , ch = 'k', pwd = "kkhkkkkvkkkkzk" }
  , Pwd { minC = 10, maxC = 13 , ch = 'g', pwd = "zgwsbgkgjgdgtsm" }
  , Pwd { minC = 4, maxC = 6 , ch = 'k', pwd = "kkkwkk" }
  , Pwd { minC = 3, maxC = 12 , ch = 'w', pwd = "gbxksbkdvjpwrjplhwvf" }
  , Pwd { minC = 1, maxC = 6 , ch = 't', pwd = "gtttsckj" }
  , Pwd { minC = 14, maxC = 15 , ch = 'w', pwd = "wwwwwwwwwwwwwzl" }
  , Pwd { minC = 2, maxC = 5 , ch = 'b', pwd = "zbblgb" }
  , Pwd { minC = 11, maxC = 12 , ch = 'm', pwd = "mtmmmmmmmmsvb" }
  , Pwd { minC = 10, maxC = 11 , ch = 't', pwd = "tttntttttmtttt" }
  , Pwd { minC = 6, maxC = 7 , ch = 'v', pwd = "vvvvvvqv" }
  , Pwd { minC = 8, maxC = 16 , ch = 'b', pwd = "bbbbgbbrxbbbbrlgb" }
  , Pwd { minC = 3, maxC = 5 , ch = 'f', pwd = "fvfpfghnvkdtpfjrf" }
  , Pwd { minC = 10, maxC = 13 , ch = 't', pwd = "rtttjtsfttttntwt" }
  , Pwd { minC = 10, maxC = 12 , ch = 'c', pwd = "ccvcccrczcccqccnj" }
  , Pwd { minC = 6, maxC = 13 , ch = 'f', pwd = "fffffkfffffffff" }
  , Pwd { minC = 9, maxC = 17 , ch = 'k', pwd = "kkkkkkkklkkkkkkkr" }
  , Pwd { minC = 6, maxC = 9 , ch = 'k', pwd = "kkkkkkkkvkkkkkkkm" }
  , Pwd { minC = 7, maxC = 8 , ch = 'g', pwd = "gnggmggmgg" }
  , Pwd { minC = 7, maxC = 8 , ch = 'l', pwd = "plllgllsll" }
  , Pwd { minC = 6, maxC = 12 , ch = 's', pwd = "sssksjxssssssfw" }
  , Pwd { minC = 7, maxC = 8 , ch = 'd', pwd = "fdddqddjddfdpmdlf" }
  , Pwd { minC = 6, maxC = 11 , ch = 'g', pwd = "gqggrggvgbgg" }
  , Pwd { minC = 2, maxC = 3 , ch = 's', pwd = "sstsqssssv" }
  , Pwd { minC = 15, maxC = 16 , ch = 'b', pwd = "sbfbbbbbbbbnbbrmbbb" }
  , Pwd { minC = 13, maxC = 14 , ch = 'z', pwd = "tbptvnfzxwlkgz" }
  , Pwd { minC = 3, maxC = 5 , ch = 'r', pwd = "rddtrrdrt" }
  , Pwd { minC = 10, maxC = 15 , ch = 'p', pwd = "pspppfppwppppwpp" }
  , Pwd { minC = 2, maxC = 4 , ch = 'j', pwd = "bsjjjgkvtw" }
  , Pwd { minC = 3, maxC = 5 , ch = 'm', pwd = "pmmmh" }
  , Pwd { minC = 6, maxC = 7 , ch = 'k', pwd = "nkdkhwsq" }
  , Pwd { minC = 3, maxC = 13 , ch = 'r', pwd = "rfrrfrrrrrrzr" }
  , Pwd { minC = 17, maxC = 19 , ch = 'r', pwd = "rrrrrrrrrrrrrdhrrrfr" }
  , Pwd { minC = 8, maxC = 10 , ch = 'n', pwd = "nnnnnbnxhnn" }
  , Pwd { minC = 5, maxC = 6 , ch = 'k', pwd = "kkkwdwkd" }
  , Pwd { minC = 14, maxC = 15 , ch = 's', pwd = "sdsgspstttvfsks" }
  , Pwd { minC = 1, maxC = 7 , ch = 't', pwd = "tttttttt" }
  , Pwd { minC = 6, maxC = 7 , ch = 'r', pwd = "cgrrmrrrrgrbcnhfmvn" }
  , Pwd { minC = 5, maxC = 18 , ch = 'v', pwd = "vkxvvsvwhvvvrvvvmrr" }
  , Pwd { minC = 3, maxC = 4 , ch = 'm', pwd = "xsmkm" }
  , Pwd { minC = 10, maxC = 12 , ch = 'q', pwd = "qqqqqqqqqqqcqqq" }
  , Pwd { minC = 1, maxC = 6 , ch = 'h', pwd = "jwhhchh" }
  , Pwd { minC = 6, maxC = 10 , ch = 'g', pwd = "ggggmdgtgg" }
  , Pwd { minC = 5, maxC = 6 , ch = 'v', pwd = "jsxvwvvsvcrzlnvqwmvq" }
  , Pwd { minC = 2, maxC = 6 , ch = 'k', pwd = "kkkkkck" }
  , Pwd { minC = 3, maxC = 6 , ch = 'w', pwd = "nckwlw" }
  , Pwd { minC = 4, maxC = 17 , ch = 'k', pwd = "wqjnlsmcskndlwpxb" }
  , Pwd { minC = 5, maxC = 7 , ch = 'f', pwd = "qrrlbfrrx" }
  , Pwd { minC = 4, maxC = 9 , ch = 'z', pwd = "czcrzzzgl" }
  , Pwd { minC = 2, maxC = 3 , ch = 't', pwd = "wttt" }
  , Pwd { minC = 1, maxC = 8 , ch = 'b', pwd = "vxbwwxrbbqsjb" }
  , Pwd { minC = 11, maxC = 12 , ch = 'g', pwd = "dxgggvbwhnrcg" }
  , Pwd { minC = 3, maxC = 6 , ch = 'j', pwd = "jjjjjjjj" }
  , Pwd { minC = 1, maxC = 10 , ch = 'v', pwd = "vvvgvvrvvjvvdvv" }
  , Pwd { minC = 2, maxC = 13 , ch = 'k', pwd = "jkgfcnqkhdkdjk" }
  , Pwd { minC = 5, maxC = 7 , ch = 'q', pwd = "kqqqhrqq" }
  , Pwd { minC = 1, maxC = 4 , ch = 'p', pwd = "npqpqpmh" }
  , Pwd { minC = 6, maxC = 7 , ch = 'x', pwd = "hmxrnxh" }
  , Pwd { minC = 4, maxC = 15 , ch = 'n', pwd = "npncnnnznnkqdnqnn" }
  , Pwd { minC = 2, maxC = 3 , ch = 'd', pwd = "dhzdd" }
  , Pwd { minC = 6, maxC = 10 , ch = 'n', pwd = "nnnnntnnnnnnn" }
  , Pwd { minC = 4, maxC = 9 , ch = 'l', pwd = "lllclllhll" }
  , Pwd { minC = 14, maxC = 16 , ch = 'n', pwd = "nnnnnnnnnnnnnvnnn" }
  , Pwd { minC = 6, maxC = 13 , ch = 'd', pwd = "sckddddfxdddvdddd" }
  , Pwd { minC = 1, maxC = 5 , ch = 'f', pwd = "hfffff" }
  , Pwd { minC = 7, maxC = 14 , ch = 'f', pwd = "fffnnfpfffjgqqdf" }
  , Pwd { minC = 9, maxC = 13 , ch = 's', pwd = "msssrsssnsssssss" }
  , Pwd { minC = 5, maxC = 8 , ch = 'j', pwd = "bjvdgjkj" }
  , Pwd { minC = 3, maxC = 5 , ch = 'q', pwd = "msqqnnb" }
  , Pwd { minC = 11, maxC = 14 , ch = 't', pwd = "ttqtttttttttttttthtt" }
  , Pwd { minC = 13, maxC = 14 , ch = 'x', pwd = "xrxxxvxxxxxxxxxxxbbx" }
  , Pwd { minC = 19, maxC = 20 , ch = 'h', pwd = "hhhhhhhhhhhhhhhhhhht" }
  , Pwd { minC = 2, maxC = 4 , ch = 'q', pwd = "wrlqgqlh" }
  , Pwd { minC = 9, maxC = 14 , ch = 'z', pwd = "zznzzzzcmvthzd" }
  , Pwd { minC = 2, maxC = 6 , ch = 'm', pwd = "qtlznmbbsznljmhd" }
  , Pwd { minC = 3, maxC = 5 , ch = 'm', pwd = "mmmmcl" }
  , Pwd { minC = 2, maxC = 6 , ch = 's', pwd = "ssnbgssnsskhssnrz" }
  , Pwd { minC = 4, maxC = 5 , ch = 'r', pwd = "rrrlr" }
  , Pwd { minC = 1, maxC = 4 , ch = 'b', pwd = "gbbb" }
  , Pwd { minC = 12, maxC = 13 , ch = 'v', pwd = "xvvvvvvvvvvkmv" }
  , Pwd { minC = 7, maxC = 15 , ch = 'b', pwd = "bbbbblgbbbbbbbbbbbbb" }
  , Pwd { minC = 3, maxC = 4 , ch = 'n', pwd = "ngpv" }
  , Pwd { minC = 3, maxC = 12 , ch = 'b', pwd = "bbbbbbbbbbbhrbbbbbbb" }
  , Pwd { minC = 19, maxC = 20 , ch = 's', pwd = "sssssssssssssssssssf" }
  , Pwd { minC = 6, maxC = 12 , ch = 'c', pwd = "jcccbckcqxcss" }
  , Pwd { minC = 2, maxC = 10 , ch = 'r', pwd = "frsbkmqqpsqdpzrvpr" }
  , Pwd { minC = 3, maxC = 12 , ch = 'p', pwd = "ppmkphqgdfphhcpd" }
  , Pwd { minC = 2, maxC = 4 , ch = 'n', pwd = "ncnn" }
  , Pwd { minC = 7, maxC = 14 , ch = 'j', pwd = "rjjjjjjjjmjjjhjjj" }
  , Pwd { minC = 6, maxC = 13 , ch = 'p', pwd = "pppfvppppppppp" }
  , Pwd { minC = 7, maxC = 8 , ch = 'h', pwd = "xhbshhhtmxvh" }
  , Pwd { minC = 6, maxC = 9 , ch = 'f', pwd = "fffffrfffffffff" }
  , Pwd { minC = 1, maxC = 6 , ch = 'd', pwd = "dddddkddd" }
  , Pwd { minC = 3, maxC = 14 , ch = 'p', pwd = "pprppppppppppppppp" }
  , Pwd { minC = 5, maxC = 6 , ch = 's', pwd = "sssssvs" }
  , Pwd { minC = 4, maxC = 13 , ch = 'z', pwd = "zzzgzzzzjzzzzx" }
  , Pwd { minC = 14, maxC = 16 , ch = 'f', pwd = "fffffffvfffffnfff" }
  , Pwd { minC = 4, maxC = 7 , ch = 'h', pwd = "xhskgbhbbbq" }
  , Pwd { minC = 5, maxC = 7 , ch = 'f', pwd = "fvffffj" }
  , Pwd { minC = 8, maxC = 9 , ch = 'g', pwd = "hxfgghdgg" }
  , Pwd { minC = 15, maxC = 17 , ch = 'w', pwd = "pxwzjdwcwwmmwnwxz" }
  , Pwd { minC = 2, maxC = 6 , ch = 'q', pwd = "pmqqqqqq" }
  , Pwd { minC = 11, maxC = 17 , ch = 'd', pwd = "cndddtdnvlnkkrfzdcz" }
  , Pwd { minC = 7, maxC = 8 , ch = 'w', pwd = "swwwwwgww" }
  , Pwd { minC = 19, maxC = 20 , ch = 'c', pwd = "ckhccpjcjcxcsccvdngh" }
  , Pwd { minC = 5, maxC = 10 , ch = 'd', pwd = "ddddddddddd" }
  , Pwd { minC = 4, maxC = 5 , ch = 'r', pwd = "rrrrrr" }
  , Pwd { minC = 2, maxC = 4 , ch = 'c', pwd = "gcccql" }
  , Pwd { minC = 5, maxC = 6 , ch = 't', pwd = "qbmqfxcsr" }
  , Pwd { minC = 2, maxC = 6 , ch = 'f', pwd = "qpfffzff" }
  , Pwd { minC = 3, maxC = 5 , ch = 'p', pwd = "lpbwph" }
  , Pwd { minC = 3, maxC = 6 , ch = 't', pwd = "ttrtttt" }
  , Pwd { minC = 2, maxC = 5 , ch = 's', pwd = "wslkz" }
  , Pwd { minC = 3, maxC = 4 , ch = 'x', pwd = "cgxt" }
  , Pwd { minC = 6, maxC = 20 , ch = 'z', pwd = "hdxggqznjfwjnlvmwsmz" }
  , Pwd { minC = 1, maxC = 4 , ch = 'l', pwd = "tkzlgkl" }
  , Pwd { minC = 5, maxC = 18 , ch = 's', pwd = "ssssrssssssssssssss" }
  , Pwd { minC = 8, maxC = 13 , ch = 'p', pwd = "wpkpcpppgwplpppp" }
  , Pwd { minC = 6, maxC = 7 , ch = 'g', pwd = "ggzxpvpdfggjrgkqdjb" }
  , Pwd { minC = 3, maxC = 9 , ch = 'b', pwd = "pqfnczzfb" }
  , Pwd { minC = 11, maxC = 12 , ch = 'l', pwd = "llllllllllxl" }
  , Pwd { minC = 17, maxC = 18 , ch = 'm', pwd = "gzjvfgvcdxmxxftlzmb" }
  , Pwd { minC = 9, maxC = 12 , ch = 'v', pwd = "wvbvvfvrvvxzvsqvfwrv" }
  , Pwd { minC = 13, maxC = 14 , ch = 'j', pwd = "jrjjjjjjjjjjjs" }
  , Pwd { minC = 2, maxC = 20 , ch = 'r', pwd = "vrvcqskfwkqrdhvtlshr" }
  , Pwd { minC = 1, maxC = 3 , ch = 'v', pwd = "wvvvr" }
  , Pwd { minC = 2, maxC = 3 , ch = 's', pwd = "tqlhxbs" }
  , Pwd { minC = 2, maxC = 19 , ch = 'j', pwd = "jjjjjjjjjjjjjjjjjjbj" }
  , Pwd { minC = 2, maxC = 8 , ch = 'h', pwd = "zphrlkvhczdgrhrm" }
  , Pwd { minC = 9, maxC = 14 , ch = 'd', pwd = "ddddbdddddddxfdd" }
  , Pwd { minC = 3, maxC = 4 , ch = 'c', pwd = "cctc" }
  , Pwd { minC = 5, maxC = 6 , ch = 'x', pwd = "xxxxxvjx" }
  , Pwd { minC = 10, maxC = 11 , ch = 's', pwd = "mvsxzpmssqx" }
  , Pwd { minC = 1, maxC = 18 , ch = 'm', pwd = "wmmmmmmmmmmmmmmmmmm" }
  , Pwd { minC = 2, maxC = 8 , ch = 'f', pwd = "vffkrwff" }
  , Pwd { minC = 11, maxC = 14 , ch = 'k', pwd = "lgknbvvkkfkcqq" }
  , Pwd { minC = 2, maxC = 4 , ch = 'n', pwd = "wcnnv" }
  , Pwd { minC = 4, maxC = 6 , ch = 'w', pwd = "wwbwnwwb" }
  , Pwd { minC = 2, maxC = 5 , ch = 'd', pwd = "jlddr" }
  , Pwd { minC = 2, maxC = 7 , ch = 'h', pwd = "hhqhfhvghzgtbfjhhshn" }
  , Pwd { minC = 2, maxC = 4 , ch = 'j', pwd = "fjjjbj" }
  , Pwd { minC = 1, maxC = 10 , ch = 'w', pwd = "wwwlwbwwsswdww" }
  , Pwd { minC = 9, maxC = 10 , ch = 'm', pwd = "mmmmmmtmmmcmc" }
  , Pwd { minC = 13, maxC = 18 , ch = 'l', pwd = "lbtllllllzllllllbdl" }
  , Pwd { minC = 5, maxC = 6 , ch = 'k', pwd = "bkckkkkkkkckkkkzb" }
  , Pwd { minC = 14, maxC = 17 , ch = 'v', pwd = "vvvvvvvvvvvvvvvvvvvv" }
  , Pwd { minC = 9, maxC = 13 , ch = 'd', pwd = "dmdpddddqtddddddvd" }
  , Pwd { minC = 10, maxC = 12 , ch = 'k', pwd = "kkkgkrkrkkktxkk" }
  , Pwd { minC = 7, maxC = 8 , ch = 'w', pwd = "hvwtwwwwwww" }
  , Pwd { minC = 6, maxC = 13 , ch = 'd', pwd = "fdpgbqbpmdmkdxkbl" }
  , Pwd { minC = 2, maxC = 3 , ch = 'm', pwd = "ctmmlm" }
  , Pwd { minC = 2, maxC = 5 , ch = 'j', pwd = "lcjjj" }
  , Pwd { minC = 8, maxC = 13 , ch = 'w', pwd = "wwwwwwwwwwwnwws" }
  , Pwd { minC = 12, maxC = 13 , ch = 'l', pwd = "lwlmlrlllcpkz" }
  , Pwd { minC = 2, maxC = 4 , ch = 'g', pwd = "xgtgg" }
  , Pwd { minC = 5, maxC = 6 , ch = 'c', pwd = "cccccrc" }
  , Pwd { minC = 3, maxC = 10 , ch = 'f', pwd = "mffnffvjxtfdjd" }
  , Pwd { minC = 1, maxC = 9 , ch = 'k', pwd = "nkkdkkkkkkk" }
  , Pwd { minC = 7, maxC = 13 , ch = 't', pwd = "wpmtclstqwtpctgcql" }
  , Pwd { minC = 3, maxC = 4 , ch = 'r', pwd = "rfrr" }
  , Pwd { minC = 6, maxC = 10 , ch = 'b', pwd = "vkbbbwzbwbbjnsrwb" }
  , Pwd { minC = 4, maxC = 7 , ch = 's', pwd = "qxlmqssqcbhstknvjzss" }
  , Pwd { minC = 3, maxC = 4 , ch = 'm', pwd = "mmfmnmmxvm" }
  , Pwd { minC = 1, maxC = 2 , ch = 'b', pwd = "cbcjhzllb" }
  , Pwd { minC = 17, maxC = 19 , ch = 'z', pwd = "zzzzzzzzzzzkzzgzzzsz" }
  , Pwd { minC = 2, maxC = 4 , ch = 'd', pwd = "ddkml" }
  , Pwd { minC = 6, maxC = 10 , ch = 'm', pwd = "nmmmmcwmmmlsm" }
  , Pwd { minC = 4, maxC = 9 , ch = 'b', pwd = "lhlbxslpxfbzzn" }
  , Pwd { minC = 5, maxC = 13 , ch = 'n', pwd = "njvdnxghhkxlsrm" }
  , Pwd { minC = 3, maxC = 4 , ch = 'p', pwd = "pppq" }
  , Pwd { minC = 1, maxC = 5 , ch = 's', pwd = "sgvrgss" }
  , Pwd { minC = 1, maxC = 13 , ch = 'h', pwd = "hhhhhhhhhhhhmfhh" }
  , Pwd { minC = 9, maxC = 11 , ch = 'w', pwd = "cwwswwwnwwbwwh" }
  , Pwd { minC = 6, maxC = 7 , ch = 'j', pwd = "jhdjjjzj" }
  , Pwd { minC = 18, maxC = 19 , ch = 'g', pwd = "ggggggggggnggggggzgg" }
  , Pwd { minC = 13, maxC = 14 , ch = 'k', pwd = "kwkkkxnpkkwkmf" }
  , Pwd { minC = 5, maxC = 6 , ch = 'f', pwd = "ffffff" }
  , Pwd { minC = 18, maxC = 20 , ch = 'c', pwd = "cccccccccccccccccfcc" }
  , Pwd { minC = 2, maxC = 5 , ch = 'd', pwd = "ddhbdbl" }
  , Pwd { minC = 10, maxC = 14 , ch = 'g', pwd = "ggwgfggjggggfhlg" }
  , Pwd { minC = 11, maxC = 13 , ch = 'q', pwd = "qqsxqfqqqqqcqwqzq" }
  , Pwd { minC = 16, maxC = 19 , ch = 'q', pwd = "fqsqtqqqqrcjqqxxwqf" }
  , Pwd { minC = 6, maxC = 7 , ch = 'w', pwd = "wwwwwwx" }
  , Pwd { minC = 6, maxC = 7 , ch = 'h', pwd = "hhhhhhp" }
  , Pwd { minC = 1, maxC = 8 , ch = 'w', pwd = "twkwwbgw" }
  , Pwd { minC = 7, maxC = 15 , ch = 'g', pwd = "ggggggkggggggggdg" }
  , Pwd { minC = 3, maxC = 5 , ch = 'j', pwd = "jjjjtjj" }
  , Pwd { minC = 1, maxC = 5 , ch = 'p', pwd = "phdppmwnfxpjpbgpppbd" }
  , Pwd { minC = 6, maxC = 10 , ch = 'b', pwd = "bbbclbbbbhbbbbb" }
  , Pwd { minC = 9, maxC = 10 , ch = 'n', pwd = "nnnnnnnnnp" }
  , Pwd { minC = 5, maxC = 6 , ch = 'n', pwd = "tktfwnqcqrv" }
  , Pwd { minC = 3, maxC = 9 , ch = 'l', pwd = "lhlxflczslf" }
  , Pwd { minC = 3, maxC = 4 , ch = 'f', pwd = "fffnvthfj" }
  , Pwd { minC = 10, maxC = 11 , ch = 'j', pwd = "gjjjjjjjjjbtj" }
  , Pwd { minC = 3, maxC = 8 , ch = 'x', pwd = "dxxcrsxxbbqrfx" }
  , Pwd { minC = 2, maxC = 3 , ch = 'h', pwd = "hfhhh" }
  , Pwd { minC = 2, maxC = 16 , ch = 'c', pwd = "wcfpjtbpgbbbnnpzchn" }
  , Pwd { minC = 7, maxC = 11 , ch = 'x', pwd = "xxrxcxxvxxfjxsvpxm" }
  , Pwd { minC = 9, maxC = 10 , ch = 'f', pwd = "fffsfffsfpfff" }
  , Pwd { minC = 2, maxC = 4 , ch = 'f', pwd = "hvcf" }
  , Pwd { minC = 9, maxC = 11 , ch = 'b', pwd = "bbbbbbbbjbp" }
  , Pwd { minC = 8, maxC = 14 , ch = 'n', pwd = "qqlxkxnnhvbdzn" }
  , Pwd { minC = 7, maxC = 10 , ch = 'v', pwd = "vvvvvvcvvgxvvvvqvp" }
  , Pwd { minC = 2, maxC = 4 , ch = 'c', pwd = "ncvw" }
  , Pwd { minC = 3, maxC = 4 , ch = 'r', pwd = "rprg" }
  , Pwd { minC = 6, maxC = 12 , ch = 'p', pwd = "tpmdppppgpppgp" }
  , Pwd { minC = 6, maxC = 7 , ch = 't', pwd = "tztrtwt" }
  , Pwd { minC = 10, maxC = 11 , ch = 'f', pwd = "qfwfcwfngds" }
  , Pwd { minC = 4, maxC = 13 , ch = 'q', pwd = "zsqqqqqtdkqgnrtqqqr" }
  , Pwd { minC = 5, maxC = 6 , ch = 'p', pwd = "phpppjpprpb" }
  , Pwd { minC = 11, maxC = 12 , ch = 'c', pwd = "cjcccccccpccp" }
  , Pwd { minC = 8, maxC = 10 , ch = 'g', pwd = "xggpbmgkfg" }
  , Pwd { minC = 9, maxC = 10 , ch = 'l', pwd = "gllllllllzl" }
  , Pwd { minC = 2, maxC = 5 , ch = 'z', pwd = "jzzjqqvp" }
  , Pwd { minC = 3, maxC = 4 , ch = 'c', pwd = "sccc" }
  , Pwd { minC = 6, maxC = 13 , ch = 'x', pwd = "xzhxgzxfxxsvxh" }
  , Pwd { minC = 7, maxC = 8 , ch = 'n', pwd = "nnnnnnxn" }
  , Pwd { minC = 18, maxC = 19 , ch = 't', pwd = "tttttfttttrttttttttt" }
  , Pwd { minC = 10, maxC = 11 , ch = 'l', pwd = "llllllfllrl" }
  , Pwd { minC = 3, maxC = 7 , ch = 'r', pwd = "tllmrjr" }
  , Pwd { minC = 3, maxC = 4 , ch = 'q', pwd = "vqntw" }
  , Pwd { minC = 1, maxC = 3 , ch = 'w', pwd = "wjwxr" }
  , Pwd { minC = 3, maxC = 12 , ch = 'z', pwd = "zwqzjfmxgtxmqvzgqnsw" }
  , Pwd { minC = 6, maxC = 7 , ch = 'm', pwd = "wmmsmhmmc" }
  , Pwd { minC = 6, maxC = 10 , ch = 'l', pwd = "lllllrllljll" }
  , Pwd { minC = 6, maxC = 8 , ch = 'n', pwd = "nnnnnnnp" }
  , Pwd { minC = 5, maxC = 8 , ch = 'h', pwd = "shqhhfhghhqhdw" }
  , Pwd { minC = 19, maxC = 20 , ch = 'l', pwd = "lnrrrbztcfsmcjkgdzlj" }
  , Pwd { minC = 3, maxC = 8 , ch = 'q', pwd = "pxqgbqsg" }
  , Pwd { minC = 1, maxC = 3 , ch = 'q', pwd = "fqrqqqqqqqqbq" }
  , Pwd { minC = 2, maxC = 7 , ch = 'k', pwd = "skcsgnk" }
  , Pwd { minC = 4, maxC = 9 , ch = 'v', pwd = "vvvvvxvvsvvvvvzvpzq" }
  , Pwd { minC = 3, maxC = 16 , ch = 'c', pwd = "ccccccccccccccccc" }
  , Pwd { minC = 10, maxC = 12 , ch = 'c', pwd = "chdpcccccccwcdvhtmc" }
  , Pwd { minC = 6, maxC = 8 , ch = 's', pwd = "sxmssfwdss" }
  , Pwd { minC = 1, maxC = 2 , ch = 'b', pwd = "hrbsckfth" }
  , Pwd { minC = 2, maxC = 4 , ch = 's', pwd = "sngs" }
  , Pwd { minC = 6, maxC = 8 , ch = 'b', pwd = "bbbgdvbb" }
  , Pwd { minC = 13, maxC = 14 , ch = 'b', pwd = "bphfdzgmhhwmbhb" }
  , Pwd { minC = 3, maxC = 4 , ch = 'h', pwd = "hhhjh" }
  , Pwd { minC = 2, maxC = 3 , ch = 'p', pwd = "cppp" }
  , Pwd { minC = 13, maxC = 14 , ch = 'r', pwd = "rrrrrrrrrrrrxr" }
  , Pwd { minC = 6, maxC = 8 , ch = 'r', pwd = "drbzrhdr" }
  , Pwd { minC = 4, maxC = 16 , ch = 'j', pwd = "cmtlnsprjjfhjgmj" }
  , Pwd { minC = 1, maxC = 10 , ch = 'm', pwd = "dfsmnmmdmm" }
  , Pwd { minC = 5, maxC = 11 , ch = 'w', pwd = "gtxwxmzwwtwrmwwwgwcd" }
  , Pwd { minC = 4, maxC = 5 , ch = 'c', pwd = "cccfcc" }
  , Pwd { minC = 3, maxC = 9 , ch = 'p', pwd = "pbpppdfpfpp" }
  , Pwd { minC = 1, maxC = 3 , ch = 'm', pwd = "nmmx" }
  , Pwd { minC = 16, maxC = 20 , ch = 'f', pwd = "ffffffffffffffflffff" }
  , Pwd { minC = 2, maxC = 13 , ch = 'v', pwd = "pvmmfzmjvvqvv" }
  , Pwd { minC = 8, maxC = 9 , ch = 'z', pwd = "wrzbzzzdz" }
  , Pwd { minC = 10, maxC = 11 , ch = 'n', pwd = "nntnnvnnncn" }
  , Pwd { minC = 14, maxC = 16 , ch = 's', pwd = "sssssssjjssssxss" }
  , Pwd { minC = 1, maxC = 13 , ch = 'p', pwd = "kppppppppppppp" }
  , Pwd { minC = 14, maxC = 15 , ch = 'w', pwd = "wwwwwwwwwwwwwmk" }
  , Pwd { minC = 3, maxC = 6 , ch = 't', pwd = "ttkdtp" }
  , Pwd { minC = 6, maxC = 7 , ch = 'd', pwd = "dddddpdd" }
  , Pwd { minC = 5, maxC = 15 , ch = 'r', pwd = "lrpsrrrrrzrrcxng" }
  , Pwd { minC = 10, maxC = 11 , ch = 'f', pwd = "ffffffffftff" }
  , Pwd { minC = 6, maxC = 10 , ch = 'l', pwd = "lllllwllflwlll" }
  , Pwd { minC = 2, maxC = 8 , ch = 'w', pwd = "rjdvtwgw" }
  , Pwd { minC = 10, maxC = 15 , ch = 'c', pwd = "cchcccccccccccjc" }
  , Pwd { minC = 6, maxC = 17 , ch = 'q', pwd = "gjlcqjvhsbjmcgxvv" }
  , Pwd { minC = 5, maxC = 11 , ch = 's', pwd = "ssssllsssssmh" }
  , Pwd { minC = 14, maxC = 16 , ch = 's', pwd = "sssssssssssssssfx" }
  , Pwd { minC = 6, maxC = 7 , ch = 'l', pwd = "lnjqdlllltlvkwnvlxs" }
  , Pwd { minC = 10, maxC = 11 , ch = 'r', pwd = "lttktskrkcx" }
  , Pwd { minC = 16, maxC = 17 , ch = 'w', pwd = "hfgdbpwkqlwfvqtwf" }
  , Pwd { minC = 2, maxC = 3 , ch = 'k', pwd = "tnkp" }
  , Pwd { minC = 13, maxC = 20 , ch = 'w', pwd = "wxrcpvvxfkxnzfvgvfkn" }
  , Pwd { minC = 14, maxC = 15 , ch = 'f', pwd = "tffffffffffffrf" }
  , Pwd { minC = 7, maxC = 8 , ch = 'q', pwd = "gqqxhtfqqqqpqm" }
  , Pwd { minC = 5, maxC = 9 , ch = 'r', pwd = "dkklrrrnh" }
  , Pwd { minC = 2, maxC = 15 , ch = 'w', pwd = "wlwwwlgmhwwgwwkwz" }
  , Pwd { minC = 4, maxC = 5 , ch = 'h', pwd = "hhhthh" }
  , Pwd { minC = 9, maxC = 11 , ch = 'x', pwd = "mxxxxxxxxqqx" }
  , Pwd { minC = 3, maxC = 6 , ch = 'f', pwd = "lzfxfmjfbgrl" }
  , Pwd { minC = 8, maxC = 9 , ch = 's', pwd = "ssstssszss" }
  , Pwd { minC = 11, maxC = 13 , ch = 't', pwd = "lrkbvdhvjzklltk" }
  , Pwd { minC = 6, maxC = 7 , ch = 'x', pwd = "xxdgxxwgx" }
  , Pwd { minC = 2, maxC = 4 , ch = 'n', pwd = "pnnn" }
  , Pwd { minC = 8, maxC = 10 , ch = 'd', pwd = "dnhlvbddxdjgvn" }
  , Pwd { minC = 4, maxC = 7 , ch = 'q', pwd = "qqqfqqqq" }
  , Pwd { minC = 2, maxC = 4 , ch = 't', pwd = "ljztcptpmz" }
  , Pwd { minC = 2, maxC = 16 , ch = 'f', pwd = "fqfffffffffffffff" }
  , Pwd { minC = 12, maxC = 13 , ch = 't', pwd = "tttttttttttxct" }
  , Pwd { minC = 9, maxC = 12 , ch = 's', pwd = "sssstssssssb" }
  , Pwd { minC = 3, maxC = 11 , ch = 'g', pwd = "nsggzgxljjlfxfl" }
  , Pwd { minC = 1, maxC = 7 , ch = 'l', pwd = "llnqshlsjl" }
  , Pwd { minC = 8, maxC = 10 , ch = 'd', pwd = "jzddhkjdwpddddddcwj" }
  , Pwd { minC = 2, maxC = 5 , ch = 'v', pwd = "rvznj" }
  , Pwd { minC = 6, maxC = 8 , ch = 'l', pwd = "lllllzljl" }
  , Pwd { minC = 1, maxC = 2 , ch = 'v', pwd = "ddvmtr" }
  , Pwd { minC = 13, maxC = 18 , ch = 's', pwd = "bspzsssrtssdvmwqss" }
  , Pwd { minC = 5, maxC = 7 , ch = 's', pwd = "ssstgss" }
  , Pwd { minC = 4, maxC = 8 , ch = 'j', pwd = "kqfknvjj" }
  , Pwd { minC = 4, maxC = 5 , ch = 'x', pwd = "xmxxx" }
  , Pwd { minC = 9, maxC = 10 , ch = 'z', pwd = "zzkzzzzzzpzzzzzz" }
  , Pwd { minC = 16, maxC = 18 , ch = 't', pwd = "dttsttttttttttnttwt" }
  , Pwd { minC = 13, maxC = 17 , ch = 'd', pwd = "dbvdddddddddpfzdd" }
  , Pwd { minC = 4, maxC = 5 , ch = 'm', pwd = "mmmmnms" }
  , Pwd { minC = 2, maxC = 3 , ch = 'f', pwd = "dlzzdhh" }
  , Pwd { minC = 3, maxC = 5 , ch = 't', pwd = "nstxrvjkjq" }
  , Pwd { minC = 2, maxC = 6 , ch = 'd', pwd = "ddfxwvd" }
  , Pwd { minC = 1, maxC = 5 , ch = 'l', pwd = "lkppsbblc" }
  , Pwd { minC = 8, maxC = 11 , ch = 'c', pwd = "ccskccccbhclc" }
  , Pwd { minC = 2, maxC = 3 , ch = 'x', pwd = "bdhx" }
  , Pwd { minC = 2, maxC = 4 , ch = 'v', pwd = "hxfhfs" }
  , Pwd { minC = 8, maxC = 10 , ch = 'f', pwd = "fgffsmfrzfqlfffmnpr" }
  , Pwd { minC = 1, maxC = 4 , ch = 'm', pwd = "qjpm" }
  , Pwd { minC = 3, maxC = 4 , ch = 'f', pwd = "fbcff" }
  , Pwd { minC = 2, maxC = 5 , ch = 't', pwd = "ttglwxxghtznp" }
  , Pwd { minC = 2, maxC = 12 , ch = 'l', pwd = "lrllllllllllll" }
  , Pwd { minC = 2, maxC = 8 , ch = 'm', pwd = "rgmnzxxmwmbdldhbpnsp" }
  , Pwd { minC = 2, maxC = 8 , ch = 'j', pwd = "jjjjjjjjjqjjj" }
  ]